REPORT_THOUGHT = [{'report_name': '现状分析', 'description': ''},
                                  {'report_name': '&nbsp;&nbsp;&nbsp;&nbsp;', 'description': '分析指标'},
                                  {'report_name': '&nbsp;&nbsp;&nbsp;&nbsp;', 'description': '日营收：每日三个渠道（抖音，美团，盈客宝）套餐营收综合'},
                                  {'report_name': '&nbsp;&nbsp;&nbsp;&nbsp;', 'description': '日售币数量：三个渠道售币总和'},
                                  {'report_name': '&nbsp;&nbsp;&nbsp;&nbsp;', 'description': '日投币：每日投币总量，入币-出币'},
                                  {'report_name': '&nbsp;&nbsp;&nbsp;&nbsp;', 'description': '币单价：（代币套餐日营收）/（日售币+日增币数量）'},
                                  {'report_name': '&nbsp;&nbsp;&nbsp;&nbsp;', 'description': '日消费：日消费=币单价*当日投币数量'},
                                  {'report_name': '&nbsp;&nbsp;&nbsp;&nbsp;', 'description': '（当日投币数量=当日总投币-当日总出币）'},
                                  {'report_name': '&nbsp;&nbsp;&nbsp;&nbsp;', 'description': '日成本：当日消耗成本=7寸娃娃机成本+8寸娃娃机成本+15寸娃娃机成本+彩票机成本+礼品机成本'},
                                  {'report_name': '&nbsp;&nbsp;&nbsp;&nbsp;', 'description': '礼品机成本=当日门店调拨出库商品明细*数量*单价'},
                                  {'report_name': '&nbsp;&nbsp;&nbsp;&nbsp;', 'description': '7寸娃娃成本=（出奖数量-回收数量）*2.55+回收数量*1.2'},
                                  {'report_name': '&nbsp;&nbsp;&nbsp;&nbsp;', 'description': '8寸娃娃成本=（出奖数量-回收数量）*5.5+回收数量*2.4'},
                                  {'report_name': '&nbsp;&nbsp;&nbsp;&nbsp;', 'description': '15寸娃娃成本=（出奖数量-回收数量）*20+回收数量*14.4'},
                                  {'report_name': '&nbsp;&nbsp;&nbsp;&nbsp;', 'description': '彩票机成本=（当日出彩票总数+当日实物票数量）/1000'},
                                  {'report_name': '套餐营收优化分析', 'description': ''},
                                  {'report_name': '&nbsp;&nbsp;&nbsp;&nbsp;', 'description': '目标：找出各个代币销售渠道中江苏南通店可优化的渠道，对于可优化渠道找出滞销套餐，进而对滞销套餐加大营销力度，提高销售额'},
                                  {'report_name': '&nbsp;&nbsp;&nbsp;&nbsp;', 'description': '1. 分析南通店可以优化的代币套餐渠道'},
                                  {'report_name': '&nbsp;&nbsp;&nbsp;&nbsp;', 'description': '2. 分析可优化渠道的滞销套餐'},
                                  {'report_name': '日营收优化分析', 'description': ''},
                                  {'report_name': '&nbsp;&nbsp;&nbsp;&nbsp;', 'description': '分析本周营收金额是否有异常情况'},
                                  {'report_name': '日成本优化分析', 'description': ''},
                                  {'report_name': '&nbsp;&nbsp;&nbsp;&nbsp;', 'description': '1.分析本周成本是否有异常情况'},
                                  {'report_name': '&nbsp;&nbsp;&nbsp;&nbsp;', 'description': '2.分析异常情况原因'},
                                  {'report_name': '游戏币优化分析', 'description': ''},
                                  {'report_name': '&nbsp;&nbsp;&nbsp;&nbsp;', 'description': '分析游戏币波动是否存在异常'},
                                  {'report_name': '会员优化分析', 'description': ''},
                                  {'report_name': '&nbsp;&nbsp;&nbsp;&nbsp;', 'description': '对比其他店铺，分析南通店的到店会员情况和会员结构占比'},
                                  {'report_name': '机台投币量优化分析', 'description': ''},
                                  {'report_name': '&nbsp;&nbsp;&nbsp;&nbsp;', 'description': '1.分析机台投币量是否存在异常'},
                                  {'report_name': '&nbsp;&nbsp;&nbsp;&nbsp;', 'description': '2.对比分析热门机器，分析是否有可优化的机器'},
                                  {'report_name': '机台异常', 'description': ''},
                                  {'report_name': '&nbsp;&nbsp;&nbsp;&nbsp;', 'description': '分析南通店第14周投币产出异常机台，出奖异常机台，故障次数异常的机台'},
]

REPORT_ANALYST = [{'analysis_item': '优化建议', 'description': '综合以上检查报告，以下为优化建议'}]
