REPORT_THOUGHT=[{'report_name': '现状分析', 'description': ''},
                                  {'report_name': '&nbsp;&nbsp;&nbsp;&nbsp;', 'description': '走势分析 - 过去2周，按日统计，每天汇总的 ACOS，点击量，转化率，CPC，广告消耗 '},
                                  {'report_name': '&nbsp;&nbsp;&nbsp;&nbsp;', 'description': '均值分析 - 过去2周，平均的 ACOS，点击量，转化率，CPC，广告消耗'},
                                  {'report_name': '统计维度解释', 'description': ''},
                                  {'report_name': '&nbsp;&nbsp;&nbsp;&nbsp;', 'description': '转化率： 7天转化率'},
                                  {'report_name': '&nbsp;&nbsp;&nbsp;&nbsp;', 'description': 'ACOS：7天转化率产生的ACOS'},
                                  {'report_name': '&nbsp;&nbsp;&nbsp;&nbsp;', 'description': '优质定义：低于平均 ACOS 10% 及以下'},
                                  {'report_name': '&nbsp;&nbsp;&nbsp;&nbsp;', 'description': '劣质定义：高于平均 ACOS 10% 及以上'},
                                  {'report_name': '&nbsp;&nbsp;&nbsp;&nbsp;', 'description': '平均ACOS计算： xx天 广告总消耗 / xx天 广告总销售额  * 100%'},
                                  {'report_name': '关键词优化分析', 'description': ''},
                                  {'report_name': '&nbsp;&nbsp;&nbsp;&nbsp;', 'description': '1，添加未在投放中的 优质 用户搜索关键词到 定向投放关键词计划中'},
                                  {'report_name': '&nbsp;&nbsp;&nbsp;&nbsp;', 'description': '2，找出 定向投放关键词 中的 优质关键词，提价操作'},
                                  {'report_name': '&nbsp;&nbsp;&nbsp;&nbsp;', 'description': '3，同类型产品广告计划中，相关的优秀关键词应该全覆盖'},
                                  {'report_name': '&nbsp;&nbsp;&nbsp;&nbsp;', 'description': '4，找出 定向投放关键词 中的 劣质关键词'},
                                  {'report_name': '商品优化分析', 'description': ''},
                                  {'report_name': '&nbsp;&nbsp;&nbsp;&nbsp;','description': '1，找出 sku广告 中的 优质广告'},
                                  {'report_name': '&nbsp;&nbsp;&nbsp;&nbsp;','description': '2，找出 sku广告 中的 劣质广告'},
                                  {'report_name': '广告计划优化分析', 'description': ''},
                                  {'report_name': '&nbsp;&nbsp;&nbsp;&nbsp;', 'description': '1，找出 campaign 广告活动 中的  优质 与 劣质广告活动'},
                                  {'report_name': '&nbsp;&nbsp;&nbsp;&nbsp;', 'description': '2，找出 campaign 广告活动 中的  placement优质位置 与 劣质位置'},
                                  {'report_name': '&nbsp;&nbsp;&nbsp;&nbsp;', 'description': '3，找出 广告 adgroup 中的  优质 与 劣质广告组'}
                                  ]
REPORT_ANALYST=[{'analysis_item': '优化策略',
                                   'description': '综合以上检查报告，以下为推荐在广告后台执行的优化策略'}]
