window.W_L = {
  'login': 'Login',
  'gg_login':'Use Google account',
  'email': "Email",
  'password': "Password",
  'remember_login': "Auto login next time",
  'submit': 'Submit',
  'forget_password': 'Forget password',
  'personal_setting': "Account Setting",
  'account': "Account",
  'activated':'Activated',
  'terminated':'Terminated',
  'has_been_deleted':'has been deleted!',
  'Cannot_enable_user':'Cannot enable user!',
  'Cannot_deactivate_user':'Cannot deactivate user!',
  'api_Key_has_been_regenerated':'API Key has been regenerated！',
  'failed_to_regenerate_api_key':'Failed to regenerate API Key!',
  'the_user_invitation_email_failed_to_be_sent':'The user invitation email failed to be sent.',
  'Cannot_delete_user':'Cannot delete user!',
  'user_invitation_email_has_been_sent':'User invitation email has been sent.',
  'the_email_server_is_not_configured':'The email server is not configured.',
  'password_reset_email_has_been_sent':'Password reset email has been sent.',
  'the_password_reset_email_was_not_sent_successfully':'The password reset email was not sent successfully.',
  'sys_status': "System Status",
  'log_out': 'Log out',
  'version': "Version",
  'task_queen_status': 'RQ Status',
  'outdated_query': 'Outdated Report',
  'queue': 'Queue',
  'query_id': "Report ID",
  'org_id': 'Org ID',
  'data_source_id':'Data Source ID',
  'user_id': 'User ID',
  'scheduled': 'Scheduled',
  'start_time': 'Start Time',
  'queue_time': 'Enqueue Time',
  'job_name': "Job Name",
  'birth_date': 'Birth Date',
  'total_work_time':'Total Working Time',
  'general': 'General',
  'no_data': 'No Data',
  'database': 'Database',
  'last_fresh': "Last Refresh",
  'started': 'Started',
  'outdated_query_count':'Outdated Report Count',
  'manage': 'Manager',
  'dashboards': "Dashboards",
  'queries': 'Report',
  'alerts': 'Alerts',
  'dialogue': 'Dialogue',
  'create': 'Create',
  'new_query':'New Report',
  'new_dashboard': "New Dashboard",
  'new_alert':'New Alert',
  'help':"Help",
  'setting': "Setting",
  'web_404': "It seems like the page you're looking for cannot be found.",
  'web_403': "It seems like you don’t have permission to see this page.",
  'web_error': "It seems like we encountered an error. Try refreshing this page or contact your administrator.",
  'unauthorized':'It seems like the page you\'re looking for cannot be found.',
  'generic': 'It seems like we encountered an error. Try refreshing this page or contact your administrator.',
  'search': "Search",
  'widget_have_no_access': "This widget requires access to a data source you don&apos;t have access to.",
  'edit':'Edit',
  'save_as_csv':'Download as CSV File',
  'save_as_tsv': 'Download as TSV File',
  'save_as_excel': 'Download as Excel File',
  'view_query': 'View Report',
  'edit_query': "Edit Report",
  'edit_param': 'Edit Parameters',
  'query_error': "Error running Report",
  'rm_fr_dashboard':"Remove from Dashboard",
  'delete_widget': "Delete Widget",
  'delete_widget_confirm': "Are you sure delete this widget?",
  'cancel': 'Cancel',
  'ok_text': 'Yes',
  'select_view': 'Choose Visualization',
  'BOXPLOT':"BOXPLOT",
  'CHART': 'CHART',
  'CHOROPLETH':'CHOROPLETH',
  'COHORT':'COHORT',
  'COUNTER': 'COUNTER',
  'DETAILS': "DETAILS",
  'FUNNEL':'FUNNEL',
  'MAP': 'MAP',
  'PIVOT': 'PIVOT',
  'SANKEY': 'SANKEY',
  'SUNBURST_SEQUENCE':'SUNBURST_SEQUENCE',
  'TABLE':'TABLE',
  'WORD_CLOUD':'WORD_CLOUD',
  'widget_not_add':'Widget could not be added',
  'add_widget':"Add Widget",
  'add_widget_to_dashboard': 'Add to Dashboard',
  'params':'Parameters',
  'save': 'Save',
  'dashboard_name':'Dashboard name',
  'close': "Close",
  'widget_will_not_add':'Widget could not be added',
  'widget_will_not_save':'Widget could not be saved',
  'quit_edit': 'Quit editing?',
  'quit_edit_confirm': 'Changes you made so far will not be saved. Are you sure?',
  'add_text': 'Add text',
  'edit_text': 'Edit text',
  'new_text': 'New text',
  'add_to_dashboard': 'Add to Dashboard',
  'input_text': 'This is where you write some text',
  'support_basic':'Supports basic',
  'open_markdown':'Markdown guide opens in new Tab',
  'open_markdown_teach':'How to use Markdown',
  'preview':'Preview',
  'upload':'Click to upload',
  'required':'This field is required.',
  'short': 'This field is too short.',
  'email_error': 'This field must be a valid email.',
  'add_params': 'Additional Settings',
  'name': 'Name',
  'this_year':'This year',
  'this_week':'This week',
  'this_month':'This month',
  'last_week':'Last week',
  'last_month':'Last month',
  'last_year':'Last year',
  'last_7_days':'Last 7 days',
  'last_14_days':'Last 14 days',
  'last_30_days':'Last 30 days',
  'last_60_days': 'Last 60 days',
  'last_90_days': 'Last 90 days',
  'last_12_months':'Last 12 months',
  'edit_view':'Edit Visualization',
  'embed_other': 'Embed Elsewhere',
  'connect_new_datasource':'Connect a Data Source',
  'ask_database_info':'Ask an account admin to connect a data source',
  'create_query':'Create your first Report',
  'create_alert':'Create new Alert',
  'create_dashboard': 'Create your first Dashboard',
  'invite_new_user': 'Invite your team members',
  'start':'Let&apos;s get started',
  'create_role':'Create role',
  'role_name':'Role name',
  'del_role':'Delete role',
  'del_role_confirm':'Are you sure delete role?',
  'del_role_success':'Delete role success',
  'add_datasource':'Add Data Sources',
  'add_user':'Add Members',
  'selected_ready': 'Already selected',
  'find_nothing': 'Sorry, we couldn\'t find anything.',
  'loading': 'Loading...',
  'can_not_delete_user':'Could not remove permission from the user',
  'mange_permissions':'Manage permissions',
  'can_not_manage_permissions':'No permission!',
  'fail_load_list':'Failed to load grantees list',
  'user_permissions':'User permissions',
  'author':'Author',
  'remove_user_permission':'Remove user permissions',
  'fail_update_api_key':'Failed to update API key',
  're_generate':'Regenerate',
  'api_example':'Example API Calls',
  'result_as_csv':'Results in CSV format',
  'result_as_json':'Results in JSON format',
  'filter_table_columns':'Filter tables & columns...',
  'search_schema': 'Search schema',
  'auto_enable':'Live Autocomplete Enabled',
  'auto_disable':'Live Autocomplete Disabled',
  'auto_info':'Live Autocomplete Not Available (Use Ctrl+Space to Trigger)',
  'not_limit':'Auto limiting is not available for this Data Source type',
  'limit_1000':'Auto limit results to first 1000 rows',
  'return_1000':' LIMIT 1000',
  'widget_add_dashboard':'Add widget to dashboard',
  'widget_add_failed':'Widget not added',
  'select_query_to_dashboard':'Choose the dashboard to add this Report to ',
  'filter_by_name':'Search a dashboard by name',
  'embed_query':'Embed Report',
  'public_url':'Public URL',
  'iframe_embed':"Iframe Embed",
  'image_embed':'Image Embed',
  'query_embed_sql_error':'Currently it is not possible to embed Report that contain text parameters',
  'auto_flush':'Refresh Schedule',
  'flush_hz':'Refresh every',
  'flush_never': 'Never',
  'on_time': 'On time',
  'on_day':"On day",
  'ends': "Ends",
  'never':"Never",
  "on":"On",
  "every":'Every',
  "at":'At',
  'flush_schema':"Refresh Schema",
  'save_success':"Saved",
  'save_failed':"Failed saving",
  'trigger':"Trigger",
  'desc':"Description",
  'query_code':'Snippet',
  'add_edit_tag':"Add/Edit Tags",
  'add_more_tag':"Add some tags",
  'add_tag':"Add tag",
  'archived':"Archive",
  'draft':'Draft',
  'archived_info':'This report is archived and can\'t be used in dashboards, or appear in search results.',
  'quit_with_not_save':"Quit with not saving?",
  'view_type':"Visualization Type",
  'view_name':"Visualization Name",
  'view_save_success':"Visualization saved",
  'view_save_failed':'Visualization could not be saved',
  'country':'Countries',
  'short_name':"Short Name",
  'full_name':'Full Name',
  'abbreviated_name':'Abbreviated name',
  'thank_you': 'Thank you',
  'setting_saved_success':'Settings Saved.',
  'share_info':'Would you be ok with sharing anonymous usage data with the develop team?',
  'help_redash':'Help us improve by automatically sending anonymous usage data',
  'redash_about_1':'Number of users, Report, dashboards, alerts, widgets and visualizations.',
  'redash_about_2':'Types of data sources, alert destinations and visualizations',
  'redash_info':'All data is aggregated and will never include any sensitive or private data.',
  'accept':'Yes',
  'reject':'No',
  'set_info_in':'You can change this setting anytime from the',
  'sys_setting':'Organization Settings',
  'sys_setting_add':'page',
  'copy':'Copy',
  'copy_success':'Copied!',
  'copy_failed':'Copy failed',
  'setting_info':'setting_info',
  'jdbc_info':'By using the Databricks Data Source you agree to the Databricks JDBC/ODBC',
  'jdbc_download_name':'Driver Download Terms and Conditions',
  'previous':"Previous",
  'done':'Done',
  'type':'Type selection',
  'type_select':'Type Selection',
  'date_select':'Select Date',
  'datetime_select':"Select Date and Time",
  'value':'Value',
  'params_name':'Choose a keyword for this parameter',
  'params_ready_exist':'Parameter with this name already exists',
  'query_show_as':'Appears in report as',
  'new_params':'Add Parameter',
  'title':"Title",
  'text':'Text',
  'number':'Number',
  'select':'Select',
  'query_result':"Report Based Dropdown List",
  'date_day':'Date',
  'date_datetime':'Date and Time',
  'date_time_second':'Date and Time (with seconds)',
  'date_range_day':'Date Range',
  'date_range_datetime':'Date and Time Range',
  'date_range_time_second':'Date and Time Range (with seconds)',
  'list_select_help':'Dropdown list values (newline delimited)',
  'wait_query':'Select report to load dropdown values from',
  'allow_multi':'Allow multiple values',
  'quotation':'Quotation',
  'replace_query_info':'Placed in report as',
  'default':'Default',
  'single_quotation':'Single Quotation Mark',
  'double_quotation':'Double Quotation Mark',
  'no_quotation':'None',
  'email_need_set':'Your mail server isn&apos;t configured correctly, and is needed for',
  'email_will_work':'Your mail server isn&apos;t configured correctly, and is needed for',
  'add_favorite':'Add to favorites',
  'remove_favorite':'Remove from favorites',
  'clear':'Clear',
  'select_all':'Select all',
  'guide_list_option':'Guide: Value Source Options',
  'guide_share_embed_dashboard':'Guide: Sharing and Embedding Dashboards',
  'guide_authentication':'Guide: Authentication Options',
  'help_share_anonymous_data':'Help: Anonymous Usage Data Sharing',
  'guide_amazon_athena':'Guide: Help Setting up Amazon Athena',
  'guide_set_bigquery':'Guide: Help Setting up BigQuery',
  'guide_set_url_port':'guide_set_url_port',
  'guide_set_mongodb':'Guide: Help Setting up MongoDB',
  'guide_set_google_spread':'Guide: Help Setting up Google Spreadsheets',
  'guide_set_google_analytics':'guide_set_google_analytics',
  'guide_set_axibase':'Guide: Help Setting up Axibase Time Series',
  'guide_set_query_result':'Guide: Help Setting up report Results',
  'guide_set_alert':'Guide: Setting Up a New Alert',
  'guide_set_mail':'guide_set_mail',
  'guide_set_notice':'Guide: Custom Alerts Notifications',
  'guide_favorite':'Guide: Managing Dashboard Favorites',
  'guide_query_permissions':'Guide: Managing Report Permissions',
  'guide_formatting_number':'Formatting Numbers',
  'guide_menu_start':'Guide: Getting Started',
  'guide_dashboard':'Guide: Dashboards',
  'guide_query':'Guide: Report',
  'guide_alert':'Guide: Alerts',
  'click_here':'Click here',
  'open_new_window':'to open the page in a new window.',
  'apply':"Apply",
  'apply_change':'Apply Changes',
  'new_dashboard_parm':'New dashboard parameter',
  'exist_dashboard_parm':'Existing dashboard parameter',
  'dashboard_param_error':'There are no dashboard parameters corresponding to this data type',
  'widget_parm':'Widget parameter',
  'static_value':'Static value',
  'enter_parm_name':'Enter a new parameter keyword',
  'select_parm':'Select from a list of existing parameters',
  'source':'Source',
  'code_mast_have_value':'Keyword must have a value',
  'exist_save_parm':'A parameter with this name already exists',
  'edit_source_value':'Edit Source and Value',
  'title_set_hidden_in_widget':'Titles for static values don\'t appear in widgets',
  'dashboard_parm':'Dashboard',
  'code':'Code',
  'default_value':'Default Value',
  'no_option':'No options available',
  'icon':'Logo/Avatar',
  'search_by_name':'Search a report by name',
  'add':'Add Items',
  'selected':'Selected items',
  'tag':'Tags',
  'loading_failed':'Failed loading status. Please refresh.',
  'started_job':'Started Jobs',
  'queen_job':'Queued Jobs',
  'queen_status':'RQ Status',
  'create_user':'Create by',
  'create_time':'Created At',
  'run_time':'Runtime',
  'last_exec_datetime':'Last Executed At',
  'update_schedule':'Update Schedule',
  'auto_update':'Auto Update',
  'last_update_time':'Last updated',
  'out_date_query':'Outdated Report',
  'alert_setting':'Alert setting',
  'add_alert_setting':'Add Existing Alert Destinations',
  'subscribed':'Subscribed.',
  'subscribe_failed':'Failed saving subscription.',
  'type_not_match_value':'Value column type doesn\'t match threshold type.',
  'type_not_match_condition':'Value column isn\'t supported by condition type.',
  'top_value':'Top row value is',
  'column_value':'Value column',
  'condition':'Condition',
  'great_then':'greater than',
  'great_and_equals':'greater than or equals',
  'less_then':'less than',
  'less_and_equals':'less than or equals',
  'equals':'equals',
  'not_equals':'not_equals',
  'threshold':'Threshold',
  'delete_alert':'Delete Alert',
  'delete_alert_confirm':'Are you sure you want to delete this alert?',
  'alert_unmute':'Unmute Notifications',
  'alert_mute':'Mute Notifications',
  'are_you_sure':'Are you sure?',
  'switch_warning':'Switching to default template will discard your custom template.',
  'use_default_template':'Use default template',
  'default_template':'Default template',
  'use_custom_template':'Use custom template',
  'custom_template':'Custom Template',
  'subject':'Subject',
  'content':'Content',
  'guide_format':'Formatting guide',
  'load_query_result':'Loading report data',
  'open_query_in_new_tab':'Open report in new tab',
  'query_not_setting':' This report has no ',
  'recommend':'Why it&apos;s recommended',
  'query_setting_tip':'A report schedule is not necessary but is highly recommended for alerts. An Alert without a report schedule will only send notifications if a user in your organization manually executes this report.',
  'second':'Second',
  'minute':'Minute',
  'hour':'Hour',
  'day':'day',
  'week':'week',
  'alert_one_time':'Just once',
  'alert_one_time_tip':'Just once until back to normal',
  'alert_every_time':'Each time alert is evaluated',
  'alert_every_time_tip':'Each time alert is evaluated until back to normal',
  'alert_most_once':'At most every',
  'alert_most_once_tip':'At most every ... when alert is evaluated',
  'notice_will_send':'Notifications are sent',
  'new_alert_tip':'New Alert',
  'can_not_edit_alert':'You cannot edit this alert',
  'no_permission_readonly':"You do not have sufficient permissions to edit this alert, and have been redirected to the view-only page.",
  'alert':'Alert',
  'alert_delete_success':'Alert deleted successfully.',
  'alert_delete_failed':'Failed deleting alert.',
  'set_mute_success':'Notifications have been muted.',
  'set_mute_failed':'Failed muting notifications.',
  'set_unmute_success':'Failed muting notifications.',
  'set_unmute_failed':'Failed restoring notifications.',
  'saving':'Saving...',
  'query':'report',
  'trigger_condition':'Trigger when',
  'trigger_send_notice':'When triggered, send notification',
  'template':'Template',
  'setup_tip':'Setup Instruction',
  'selector_query_tip':'Start by selecting the report that you would like to monitor using the search bar. Keep in mind that Alerts do not work with Report that use parameters.',
  'status':'Status',
  'alert_setting_sure':'Alert condition has not been evaluated.',
  'last_trigger_time':'Last triggered',
  'no_permission_edit_alert':'You do not have sufficient permissions to edit this alert',
  'notice':'Notifications',
  'set':'Set',
  'custom':'Custom',
  'notice_template':'notification template.',
  'set_mute':'Mute',
  'set_unmute':'Unmute',
  'alert_not_sent_info':'Notifications for this alert will not be sent.',
  'reset_alert_sent_info':'To restore notifications click',
  'destination':'Destinations',
  'set_alert_open_tab':'Open Alert Destinations page in a new tab.',
  'get_notice_event':'Get notified on certain events',
  'auto_flush_hz':'Auto Refreshing every ',
  'flush':'Refresh',
  'stop_auto_flush':'Disable auto refresh',
  'dashboard_archived':'Archive Dashboard',
  'publish':'Publish',
  'dis_en_able_fullscreen':'Enable/Disable Fullscreen display',
  'share_dashboard_setting':'Dashboard Sharing Options',
  'saved':'Saved',
  'retry':'Retry',
  'need_help':'Need help',
  'create_first_dashboard':'Create your first dashboard!',
  'see_big_picture':'See the big picture',
  'show_my_favorite_dashboard':'Mark dashboards as Favorite to list them here.',
  'share_dashboard':'Share Dashboard',
  'share_dashboard_tip':'Allow public access to this dashboard with a secret address.',
  'open_share_dashboard_failed':'Failed to turn on sharing for this dashboard',
  'close_share_dashboard_failed':'Failed to turn off sharing for this dashboard',
  'allow_public':'Allow public access',
  'secret_address':'Secret address',
  'secret_address_tip':'For your security, sharing is currently not supported for dashboards containing Report with text parameters. Consider changing the text parameters in your report to a different type.',
  'dashboard_has_changed':'It seems like the dashboard has been modified by another user.',
  'dashboard_has_changed_tip':'Please copy/backup your changes and reload this page.',
  'all_dashboard':'All Dashboards',
  'my_dashboard':'My Dashboards',
  'my_favorite_dashboard':'Favorites',
  'search_dashboard':'Search dashboards',
  'dashboard_filter':'Use Dashboard Level Filters',
  'dashboard_widget_info':'Widgets are individual report visualizations or text boxes you can place on your dashboard in various arrangements',
  'data_source':'Data Sources',
  'new_data_source':'New Data Source',
  'no_datasource':'There are no data sources yet.',
  'datasource_delete_success':"Data source deleted successfully.",
  'delete_datasource':'Delete Data Source',
  'delete_datasource_confirm':'Are you sure you want to delete this data source',
  'connect_success':'Success',
  'connect_failed':'Connection Test Failed',
  'connect_failed_tip':'Unknown error occurred while performing connection test. Please try again later.',
  'delete':'Delete',
  'connect_test':'Test Connection',
  'no_alert_setting':'There are no alert destinations yet.',
  'user':'Members',
  'full_access':'Full access',
  'view_only':'View Only',
  'datasource_delete_failed':'Failed to remove data source from group.',
  'change_datasource_permission_failed':'Failed change data source permissions.',
  'search_database':'Search data sources',
  'group_datasource':'Group Data Sources',
  'group_no_datasource':'There are no data sources in this group yet.',
  'remove':"Remove",
  'add_member':'Add members',
  'search_member':'Search members',
  'remove_member_failed':'Failed to remove member from group.',
  'role_no_member':'There are no members in this group yet.',
  'role':'Groups',
  'built_in':'Built-in',
  'built_in_role_delete_tip':'Cannot delete built-in group',
  'my_favorite_query':'Favorite Report',
  'email_send':'We have sent an email with a confirmation link to your email address. Please follow the link to verify your email address.',
  're_send_email':'Resend email',
  'redash_welcome':'Welcome!',
  'redash_desc':'Connect to any data source, easily visualize and share your data',
  'redash_cut_data_tip':'rows. Databricks may truncate report results that are unstably large',
  'running':'Running',
  'flush_time':'Refreshed',
  'query_queue':'Report in queue',
  'exec_query':'Executing',
  'loading_query_result':'Loading results',
  'query_run_error':'Error running report',
  'update_time':'updated',
  'show':'Show',
  'edit_source':'Edit Source',
  'show_result_only':'Show Results Only',
  'no_datasource_cant_create_query':'You don\'t have permission to create new Report on any of the data sources available to you.',
  'apply_permission':'You can either <Link href="Report">browse existing Report</Link>, or ask for additional permissions from your admin.',
  'no_datasource_or_permission':' Looks like no data sources were created yet or none of them available to the group(s) you\'re member of.',
  'first_create_datasource':'Please create one first, and then start querying.',
  'delete_view':'Delete Visualization',
  'delete_view_confirm':'Are you sure you want to delete this visualization?',
  'table':'Table',
  'add_view':"Add Visualization",
  'please_exec_flush':'Execute/Refresh the report to show results',
  'no_permission_exec':'You do not have a permission to execute/refresh this report',
  'archived_search':'Archive Report',
  'archived_confirm':'Are you sure you want to archive this report?',
  'archived_tip':'All alerts and dashboard widgets created with its visualizations will be deleted.',
  'archived_failed':'Report could not be archived.',
  'flush_error':'Schema refresh failed.',
  'wait_retry':'Please try again later.',
  'query_save_publish_success':'Report saved and published',
  'leave_lost_warning':'You will lose your changes if you leave',
  'leave_lost_confirm':'Are you sure you want to leave this page',
  'change_not_save':'Changes not saved',
  'query_has_change':'It seems like the report has been modified by another user.',
  'self_copy_save_and_reload':'Please copy/backup your changes and reload this page.',
  'overwrite_query':'Over write report',
  'overwrite_query_confirm':'Are you sure you want to overwrite the report with your version?',
  'new_desc':'Add description',
  'query_format':'Format Report',
  'query_format_not_support':'Report formatting is not supported for your Data Source syntax',
  'exec_select_query':'Execute Selected',
  'flush_now':'Flush Now',
  'toggle_screen':'Toggle Fullscreen',
  'open_in_redash':'Open in new Web',
  'save_as':'Download Dataset',
  'view_not_exist':'Visualization does not exist',
  'all_queries':'All Report',
  'my_queries':'My Report',
  'archived_query':'Archived Report',
  'search_query':'search_report',
  'get_data_from_datasource':'Getting the data from your datasources.',
  'script':'Snippet',
  'snippet_script':'Report Snippet',
  'delete_snippet_script':'Delete Report Snippet',
  'delete_snippet_script_confirm':'Are you sure you want to delete this report snippet?',
  'delete_snippet_script_success':'Report snippet deleted successfully.',
  'delete_snippet_script_failed':'Failed deleting report snippet.',
  'new_snippet_script':'New Report Snippet',
  'no_snippet_script':'There are no report snippets yet.',
  'google_login':'Google Login',
  'allow':'Allow',
  'google_login_tip':'Any user registered with a',
  'google_login_auto_reg':'Google Apps account will be able to login. If they don\'t have an existing user, a new user will be created and join the default group',
  'authentication':'Authentication',
  'disable_password_tip':'assword based login is currently disabled and users will be able to login only with the enabled SSO options.',
  'password_login':'Password Login',
  'enable_password_login_tip':'Password login can be disabled only if another login method is enabled',
  'enable_password':'Password Login Enabled',
  'enable_saml':'SAML Enabled',
  'disable':'Disable',
  'enable':"Enable",
  'static':'Static',
  'dynamic':'Dynamic',
  'help_redash_improve_tip':'Help us improve by automatically sending anonymous usage data',
  'feature_flags':'Feature Flags',
  'enable_multiple_owners_tip':'Enable experimental multiple owners support',
  'when_query_error_info_by_email':'Email report owners when scheduled Report fail',
  'dashboard_language_tip':'Enable multi-byte (Chinese, Japanese, and Korean) search for report names and descriptions (slower)',
  'date_format':'Date Format',
  'time_format':'Time Format',
  'table_view':'Chart Visualization',
  'hidden_tool_bar':'Hide Plotly mode bar',
  'too_short':'This field is too short.',
  'do_not_match':'do_not_match',
  'change_password':'Change Password',
  'current_password':'Current Password',
  'new_password':'New Password',
  'repeat_password':'Repeat New Password',
  'email_send_error':'Email not sent!',
  'email_not_setting':'The mail server is not configured, please send the following link to',
  'email_reset_password_send':'Send Password Reset Email',
  'email_re_send_invite':'Resend Invitation',
  're_generate_api_key':'Regenerate API Key',
  're_generate_api_key_confirm':'Are you sure you want to regenerate?',
  'user_name':'Name',
  'enable_user':'Enable User',
  'disable_user':'Disable User',
  'invite_email':'invite emails',
  'invite_user':'Pending Invitations',
  'active_time':'Last Active At',
  'unpublished':"Unpublished",

  'connection_failed':'Connection failed',
  'connection_success_tip':'Connection succeeded',
  'connection_failed_tip':'Connection failed, reconnecting',
  'connection_success':'Database configuration completed',
  'select_data_source':'Select data source',
  'enter_your_question':'Enter your question',
  'connection_seems_lost':'Connection seems lost, please retry',
  'stopping_generation':'Stopping generation...',
  'please_fill_in_the_description':'Please fill in the description',
  'configuration_completed':'Configuration completed',
  'start_the_dialogue':'Start the dialogue',
  'report_generation_completed':'Report generation completed',
  'stop_generation':'Stop',
  'send_me_instructions':'Send a message',
  'start_use':'Start using',
  'init_config':'Initializing configuration',
  'table_desc':'Table description',
  'select_table':'Select table...',
  'table_field_desc_edit':'Table field description edit',
  'language_mode':"EN",
  'excel_upload':'CSV Data Source',
  'data_analysis':'Data Copilot',
  'report_generation':'Report Generation',
  'report_list':'Report List',
  'dashboard':'Dashboard',
  'offline':'Offline',
  'online':'Online',
  'pending':'Pending',
  'temporary_dashboard':'Temporary Dashboard',
  'dialogue_list':'Dialogue List',
  'history_dialogue':'History Dialogue',

  'reset_dialogue':'Reset Dialogue',
  'reset_dialogue_confirm':'Are you sure you want to create a new conversation and reset the current conversation?',
  'new_dialogue':'New Dialogue',

  'chat_start':'Please choose your data source & table to start data analysis or',
  'report_start':'Please choose your data source & table to start report generation or',
  'AutoPilot_start':'Please choose your data source & table to start AutoPilot, or',
  'sheet_description':'Please fill in the data sheet description',
  'field_description':'Please fill in the data sheet field description',
  'source_tooltip':'Select your data source and complete the corresponding table and field descriptions, DeepBI enables you to translate human Languageuage into Xusable actions and helps you complete real-world tasks, such as those related to your data.',
  'source_first_tooltip':'Please complete the form and field comments so that the Agent can better help you complete the task.',
  'source_second_tooltip':'The above comments did not pass the large model detection, please modify and submit again.',

  'fail':'Fail',
  'pass':'Pass',
  'detection':'Detection',
  'description':'Description',
  'field_name':'Field Name',
  'universal_csv':'Universal CSV',
  'ai_understanding_data':'AI is trying to understand the data, please wait patiently...',

  'start_your_dialogue':'Start your dialogue to generate a report',
  'no_dialogue':'No dialogue record',
  'new_Query':'New Report',
  'query_builder': 'Query Builder',
  'empty_query':'Empty statement cannot be executed.',

  'left_align': 'Left Align',
  'center': 'Center',
  'right_align': 'Right Align',
  'formatting_numbers': 'Formatting Numbers',
  'formatting_dates_and_times': 'Formatting Dates and Times',
  'x_axis_label': 'X-Axis Label',
  'y_axis_label': 'Y-Axis Label',
  'scale': 'Scale',
  'auto_detect': 'Auto Detect',
  'datetime': 'Datetime',
  'linear': 'Linear',
  'logarithmic': 'Logarithmic',
  'category': 'Category',
  'auto': 'Auto',
  'min_value': 'Min Value',
  'max_value': 'Max Value',
  'x_column': 'X Column',
  'y_column': 'Y Column',
  'group_by': 'Group By',
  'errors_column': 'Errors Column',
  'color_column': 'Color Column',
  'choose_columns...': 'Choose Columns...',
  'choose_column..': 'Choose Column...',
  'color': 'Color',
  'series': 'Series',
  'bubble_size_coefficient': 'Bubble Size Coefficient',
  'bubble_size_proportional_to': 'Bubble Size Proportional To',
  'direction': 'Direction',
  'legend_placement': 'Legend Placement',
  'legend_items_order': 'Legend Items Order',
  'stacking': 'Stacking',
  'missing_and_NULL_values': 'Missing and NULL Values',
  'color_scheme': 'Color Scheme',
  'choose_color_scheme': 'Choose Color Scheme',
  'min_color': 'Min Color',
  'max_color': 'Max Color',
  'data_labels': 'Data Labels',
  'order': 'Order',
  'label': 'Label',
  'y_axis': 'Y-Axis',
  'x_axis': 'X-Axis',
  'left_y_axis': 'Left Y-Axis',
  'right_y_axis': 'Right Y-Axis',
  'reverse_order': 'Reverse Order',
  'sort_values': 'Sort Values',
  'align_Y_axes_at_zero': 'Align Y-Axes at Zero',
  'columns': 'Columns',
  'grid': 'Grid',
  'items_per_page': 'Items per Page',
  'toggle_visibility': 'Toggle Visibility',
  'Link': 'Link',
  'Image': 'Image',
  'URL_template': 'URL Template',
  'Text_template': 'Text Template',
  'Title_template': 'Title Template',
  'Open_in_new_tab': 'Open in New Tab',
  'All_columns_can_be_referenced_using': 'All columns can be referenced using',
  'syntax': 'syntax.',
  'This_syntax_is_applicable_to_URL_Text_and_Title_options': 'This syntax is applicable to URL, Text, and Title options.',
  'Use': 'Use',
  'to_reference_current_this_column': 'to reference the current/this column.',
  'Width': 'Width',
  'Height': 'Height',
  'Leave_empty_to_use_default_value': 'Leave empty to use default value.',
  'Any_positive_integer_value_that_specifies_size_in_pixels': 'Any positive integer value that specifies size in pixels.',
  'Size': 'Size',
  'Boolean': 'Boolean',
  'Highlight_links': 'Highlight Links',
  'Allow_HTML_content': 'Allow HTML Content',
  'Number_format': 'Number Format',
  'Date_Time_format': 'Date Time Format',
  'Value_for': 'Value for',
  'Error_while_rendering_visualization': 'Error while rendering visualization.',
  'Show_Data_Labels': 'Show Data Labels',
  'Percent_Values_Format': 'Percent Values Format',
  'Data_Labels': 'Data Labels',
  'using': 'using',
  'Also_all_query_result_columns_can_be_referenced': 'Also, all query result columns can be referenced.',
  'Horizontal_Chart': 'Horizontal Chart',
  'Area': 'Area',
  'Diameter': 'Diameter',
  'Counterclockwise': 'Counterclockwise',
  'Clockwise': 'Clockwise',
  'Hide_legend': 'Hide Legend',
  'Right': 'Right',
  'Bottom': 'Bottom',
  'Normal': 'Normal',
  'Reversed': 'Reversed',
  'Show_All_Points': 'Show All Points',
  'Disabled': 'Disabled',
  'Stack': 'Stack',
  'Normalize_values_to_percentage': 'Normalize values to percentage',
  'Do_not_display_in_chart': 'Do not display in chart',
  'Convert_to_0_and_display_in_chart': 'Convert to 0 and display in chart',
  'Left': 'Left',
  'Show_Labels': 'Show Labels',
  'North_East_Latitude_and_Longitude': 'North-East Latitude and Longitude',
  'South_West_Latitude_and_Longitude': 'South-West Latitude and Longitude',
  'Clustering_Mode': 'Clustering Mode',
  'Steps': 'Steps',
  'No_Value_Color': 'No Value Color',
  'Background_Color': 'Background Color',
  'Borders_Color': 'Borders Color',
  'Stage_Value': 'Stage Value',
  'Map': 'Map',
  'Key_Column': 'Key Column',
  'Target_Field': 'Target Field',
  'Value_Column': 'Value Column',
  'Time_Column_Title': 'Time Column Title',
  'People_Column_Title': 'People Column Title',
  'Stage_Column_Title': 'Stage Column Title',
  'No_Value_Placeholder': 'No Value Placeholder',
  'Show_Tooltips': 'Show Tooltips',
  'Daily': 'Daily',
  'Weekly': 'Weekly',
  'Monthly': 'Monthly',
  'Fill_gaps_with_zeros': 'Fill gaps with zeros',
  'Show_data_as_is': 'Show data as is',
  'Time_Interval': 'Time Interval',
  'Mode': 'Mode',
  'Items_Count_Limit': 'Items Count Limit',
  'Min_Percent_Value': 'Min Percent Value',
  'Max_Percent_Value': 'Max Percent Value',
  'number_of_times_this_sequence_occurred': 'Number of times this sequence occurred',
  'stage_5_value_or_null': 'Stage 5 Value (or null)',
  'stage_4_value_or_null': 'Stage 4 Value (or null)',
  'stage_3_value_or_null': 'Stage 3 Value (or null)',
  'stage_2_value_or_null': 'Stage 2 Value (or null)',
  'stage_1_value': 'Stage 1 Value',
  'Option': 'Option',
  'stage_name': 'Stage Name',
  'what_stage_in_sequence_this_is_1_2': 'What stage in the sequence this is (1, 2, ...)',
  'sequence_id': 'Sequence ID',
  'This_visualization_expects_the_query_result_to_have_rows_in_one_of_the_following_formats': 'This visualization expects the query result to have rows in one of the following formats',
  'Show_Column_Totals': 'Show Column Totals',
  'Show_Row_Totals': 'Show Row Totals',
  'Show_Pivot_Controls': 'Show Pivot Controls',
  'Icon_Color': 'Icon Color',
  'Enter_an_icon_name_from': 'Enter an icon name from',
  'Examples': 'Examples',
  'Leave_blank_to_remove': 'Leave blank to remove.',
  'Map_Tiles': 'Map Tiles',
  'Markers': 'Markers',
  'Cluster_Markers': 'Cluster Markers',
  'Override_default_style': 'Override default style',
  'Shape': 'Shape',
  'Circle': 'Circle',
  'Circle_Dot': 'Circle Dot',
  'Square_Dot': 'Square Dot',
  'Square': 'Square',
  'Longitude_Column_Name': 'Longitude Column Name',
  'Latitude_Column_Name': 'Latitude Column Name',
  'Popup_template': 'Popup Template',
  'Show_popup': 'Show Popup',
  'Tooltip_template': 'Tooltip Template',
  'Show_tooltip': 'Show Tooltip',
  'Legend_Text_Alignment': 'Legend Text Alignment',
  'Legend_Position': 'Legend Position',
  'Show_Legend': 'Show Legend',
  'Value_Placeholder': 'Value Placeholder',
  'Value_Format': 'Value Format',
  'auto_pilot': 'Data Autopilot',
  'report_desc': 'Report Description',
  'report_name': 'Report Name',
  'report_desc_placeholder': 'Please enter a description of the report',
  'report_name_placeholder': 'Please enter the name of the report',
  'history_autopilot': 'History Autopilot',
  'task_status':'Task Status',
  'no_analysis_available':'No analysis available',
  'success':'Success',
  'fail':'Fail',
  'generating':'Generating',
  'waiting':'Waiting',
  'all_autopilot':'All Autopilot',
  'submit_success':'Submitted successfully',
  'submit_success_tip':'You can view it in the history analysis',
  'submit_fail':'Submission failed',
  'download':'Download',
  'please_enter_api_key':'Please enter the API key',
  'please_enter_api_host':'Please enter the API host',
  'confirm_delete':'Confirm Delete',
  'confirm_delete_tip':'Are you sure you want to delete this item?',
  'please_complete_report_name_and_report_desc':'Please report a complete name and report description and let the Agent perform automatic data analysis for you.',
  'report_name_and_report_desc_tip':'The report name will be used as the title of the generated report; the report description agent provides the general direction of automatic data analysis and delineates the analysis scope for your report; click Submit and a report task will be created',
  'report_name_tip':'The report name will be used as the title of the generated report',
  'report_desc_tip':'The report description agent provides the general direction of automatic data analysis and delineates the analysis scope for your report',
  'task_processing':'Task Processing...',
  'formatting':'Formatting',
  'border':'Border',
  'exterior':'Exterior',
  'style':'Style',
  "region": "Region",
  "column": "Column",
  "option": "Option",
  'click_here_to_get_apikey':'Click here to get API key',
  'dashboards_prettify':'Dashboards Prettify',
  'dashboards_prettify_all':'Dashboards Prettify',
  'delete_success':'Delete Success',
  'delete_fail':'Delete Fail',
  'no_dashboard_data':'No dashboard data',
  'prettify_dashboard':'Prettify Dashboard',
  'coming_soon':'Coming Soon',
  'example1':'Example1',
  'example2':'Example2',
  'example3':'Example3',
  'more':'More',
}
