// JA
window.W_L=  {
    // 日语
    'login': 'ログイン',
    'gg_login':'Googleログイン',
    'email': "メールアドレス",
    'password': "パスワード",
    'remember_login': 'ログインを記憶する',
    'submit': '提出する',
    'forget_password': "パスワードを忘れる",
    'personal_setting': '個人設定',
    'account': "ユーザー",
    'activated':'アクティブ化された',
    'terminated':'終了しました',
    'has_been_deleted':'削除されました！',
    'Cannot_enable_user':'ユーザーを有効にできません!',
    'Cannot_deactivate_user':'ユーザーを非アクティブ化できません!',
    'Cannot_delete_user':'ユーザーを削除できません!',
    'sys_status': 'システムステータス',
    'log_out': 'やめる',
    'version': 'バージョン',
    'task_queen_status': 'タスクキューのステータス',
    'outdated_query': '超期报表',
    'queue': '队列',
    'query_id': "报表ID",
    'org_id': "组织ID",
    'data_source_id': '数据源ID',
    'user_id': '用户ID',
    'scheduled': '调度中',
    'start_time': '开始时间',
    'queue_time': "进入队列时间",
    'job_name': '任务名称',
    'birth_date': '创建时间',
    'total_work_time': '运行总时长',
    'general': '通用',
    'no_data': '无数据',
    'database': "数据库",
    'last_fresh': "最后刷新",
    'started': '运行中',
    'outdated_query_count':"超期报表数",
    'manage': "管理",
    'dashboards': "仪表盘",
    'queries': '报表',
    'query_builder': '报表',
    'alerts': '提醒',
    'dialogue': '对话',
    'create':"新建",
    'new_query': "新建报表",
    'new_dashboard': "新建仪表盘",
    'new_alert':'新建提醒',
    'help':"帮助",
    'setting': "设置",
    'web_404': "网页不存在",
    'web_403': "没有权限",
    'web_error': "系统出错，请刷新重试或者联系系统管理员！",
    'unauthorized':'没有权限',
    'generic':'系统出错，请联系管理员。',
    'search': '搜索',
    'widget_have_no_access':"没有部件来源数据源权限!",
    'edit': '编辑',
    'save_as_csv':"另存为CSV文件",
    'save_as_tsv': "另存为TSV文件",
    'save_as_excel': "另存为Excel文件",
    'view_query': "查看报表",
    'edit_query': "编辑报表",
    'edit_param': "编辑参数",
    'query_error':"报表运行错误",
    'rm_fr_dashboard':'从仪表盘中删除',
    'delete_widget': '删除组件',
    'delete_widget_confirm':"确定删除该组件么?",
    'cancel': '取消',
    'ok_text': '确定',
    'select_view': '选择视图',
    'BOXPLOT':"箱线图",
    'CHART':"图表",
    'CHOROPLETH':"地理分布图",
    'COHORT':'同期群分析',
    'COUNTER':"计数器",
    'DETAILS': "记录明细显示",
    'FUNNEL': '漏斗分析',
    'MAP': '地图标记',
    'PIVOT': '数据透视表',
    'SANKEY': '桑基图',
    'SUNBURST_SEQUENCE': '旭辉图',
    'TABLE':'表格',
    'WORD_CLOUD':'词云图',
    'widget_not_add': "部件未能添加",
    'add_widget':'添加部件',
    'add_widget_to_dashboard':'添加部件',
    'params': "参数",
    'save':"保存",
    'dashboard_name':'仪表盘名称',
    'close':"关闭",
    'widget_will_not_add':'部件不会添加',
    'widget_will_not_save':'部件不会保存',
    'quit_edit':'退出编辑',
    'quit_edit_confirm': '更改内容将不会保存，确定退出吗?',
    'add_text':"新增文本",
    'edit_text':"编辑文本",
    'new_text':"新文本",
    'add_to_dashboard':"添加到仪表盘",
    'input_text':"请输入新文本",
}