window.W_L=  {
    'login': 'ログイン',
    'gg_login':'Googleでログイン',
    'email': "メール",
    'password': 'パスワード',
    'remember_login': '次回から自動的にログイン',
    'submit': '提出',
    'forget_password': "パスワードを忘れた",
    'personal_setting': '個人設定',
    'account': "アカウント",
    'activated':'有効化されました',
    'terminated':'終了しました',
    'has_been_deleted':'削除されました！',
    'Cannot_enable_user':'ユーザーを有効にできません！',
    'Cannot_deactivate_user':'ユーザーを無効にできません！',
    'Cannot_delete_user':'ユーザーを削除できません！',
    'sys_status': 'システムステータス',
    'log_out': 'ログアウト',
    'version': 'バージョン',
    'task_queen_status': 'タスクキューのステータス',
    'outdated_query': '期限切れのクエリ',
    'queue': 'キュー',
    'query_id': "クエリID",
    'org_id': "組織ID",
    'data_source_id': 'データソースID',
    'user_id': 'ユーザーID',
    'scheduled': 'スケジュールされた',
    'start_time': '開始時間',
    'queue_time': "キュー入り時間",
    'job_name': 'ジョブ名',
    'birth_date': '作成時間',
    'total_work_time': '総作業時間',
    'general': '一般',
    'no_data': 'データなし',
    'database': "データベース",
    'last_fresh': "最後の更新",
    'started': '開始された',
    'outdated_query_count':"期限切れのクエリ数",
    'manage': "管理",
    'dashboards': "ダッシュボード",
    'queries': 'クエリ',
    'query_builder': 'クエリビルダー',
    'alerts': 'アラート',
    'dialogue': 'ダイアログ',
    'create':"作成",
    'new_query': "新しいクエリ",
    'new_dashboard': "新しいダッシュボード",
    'new_alert':'新しいアラート',
    'help':"ヘルプ",
    'setting': "設定",
    'web_404': "ページが見つかりません",
    'web_403': "権限がありません",
    'web_error': "システムエラーが発生しました。再度試してみてください。",
    'unauthorized':'権限がありません',
    'generic':'システムエラーが発生しました。管理者に連絡してください。',
    'search': '検索',
    'widget_have_no_access':"ウィジェットのデータソースへのアクセス権がありません!",
    'edit': '編集',
    'save_as_csv':"CSVファイルとして保存",
    'save_as_tsv': "TSVファイルとして保存",
    'save_as_excel': "Excelファイルとして保存",
    'view_query': "クエリを見る",
    'edit_query': "クエリを編集",
    'edit_param': "パラメータを編集",
    'query_error':"クエリエラー",
    'rm_fr_dashboard':'ダッシュボードから削除',
    'delete_widget': 'ウィジェットを削除',
    'delete_widget_confirm':"このウィジェットを削除してもよろしいですか?",
    'cancel': 'キャンセル',
    'ok_text': 'OK',
    'select_view': 'ビューを選択',
    'BOXPLOT':"ボックスプロット",
    'CHART':"チャート",
    'CHOROPLETH':"コロプレス図",
    'COHORT':'コホート分析',
    'COUNTER':"カウンター",
    'DETAILS': "詳細レコード表示",
    'FUNNEL': 'ファネル分析',
    'MAP': 'マップマーカー',
    'PIVOT': 'ピボットテーブル',
    'SANKEY': 'サンキーダイアグラム',
    'SUNBURST_SEQUENCE': 'サンバースト図',
    'TABLE':'テーブル',
    'WORD_CLOUD':'ワードクラウド',
    'widget_not_add': "ウィジェットが追加されませんでした",
    'add_widget':'ウィジェットを追加',
    'add_widget_to_dashboard':'ウィジェットを追加',
    'params': "パラメータ",
    'save':"保存",
    'dashboard_name':'ダッシュボード名',
    'close':"閉じる",
    'widget_will_not_add':'ウィジェットは追加されません',
    'widget_will_not_save':'ウィジェットは保存されません',
    'quit_edit':'編集を終了',
    'quit_edit_confirm': '変更内容は保存されません。終了してもよろしいですか?',
    'add_text':"テキストを追加",
    'edit_text':"テキストを編集",
    'new_text':"新しいテキスト",
    'add_to_dashboard':"ダッシュボードに追加",
    'input_text':"新しいテキストを入力してください",
    'support_basic':'基本的なサポート',
    'open_markdown':'新しいウィンドウでMarkdownガイドを開く',
    'open_markdown_teach':"Markdownチュートリアル",
    'preview':'プレビュー',
    'upload':"アップロードをクリック",
    'required': '必須項目は空にできません',
    'short': '内容が短すぎます!',
    'email_error':"Emailの形式が正しくありません",
    'add_params':'パラメータを追加',
    'name': '名前',
    'this_year':'今年',
    'this_week':'今週',
    'this_month':'今月',
    'last_week':'先週',
    'last_month':'先月',
    'last_year':'去年',
    'last_7_days':'過去7日間',
    'last_14_days':'過去14日間',
    'last_30_days':'過去30日間',
    'last_60_days': '過去60日間',
    'last_90_days': '過去90日間',
    'last_12_months':'過去12ヶ月',
    'edit_view':"ビューを編集",
    'embed_other':"他に埋め込む",
    'connect_new_datasource':'新しいデータソースに接続',
    'ask_database_info' :"データソースは接続アカウント情報を必要とします",
    'create_query':"新しいクエリを作成",
    'create_alert':'新しいアラートを作成',
    'create_dashboard': '新しいダッシュボードを作成',
    'invite_new_user': 'チームメンバーを招待',
    'start':'開始',
    'create_role':'新しいロールを作成',
    'role_name':'ロール名',
    'del_role':'ロールを削除',
    'del_role_confirm':'ロールを削除してもよろしいですか?',
    'del_role_success':'ロールの削除に成功しました',
    'add_datasource':'データソースを追加',
    'add_user':'ユーザーを追加',
    'selected_ready':'選択済み',
    'find_nothing':'データが見つかりません',
    'loading':'読み込み中',
    'can_not_delete_user':'ユーザーを削除できません',
    'mange_permissions':'権限管理',
    'can_not_manage_permissions':'権限を管理できません',
    'fail_load_list':"権限リストの読み込みに失敗しました",
    'user_permissions':'ユーザー権限',
    'author':'著者',
    'remove_user_permission':'ユーザー権限を削除',
    'fail_update_api_key':'Api Keyの更新に失敗しました',
    're_generate':'再生成',
    'api_example':'Api呼び出し例',
    'result_as_csv':'結果をCSV形式で出力',
    'result_as_json':'結果をJSON形式で出力',
    'filter_table_columns':'テーブルと列をフィルタリング',
    'search_schema': 'データテーブル列を検索',
    'auto_enable':'自動補完を有効にする',
    'auto_disable':'自動補完を無効にする',
    'auto_info':'自動補完が無効になっています (Ctrl+Spaceで有効にする)',
    'not_limit':'このタイプのデータソースは結果の数を制限できません',
    'limit_1000':'結果セットを最初の1000行に制限',
    'return_1000':'最初の1000行を返す',
    'widget_add_dashboard':'ウィジェットをダッシュボードに追加',
    'widget_add_failed':'ウィジェットの追加に失敗しました',
    'select_query_to_dashboard':'ダッシュボードに追加するクエリを選択してください',
    'filter_by_name':'名前でダッシュボードを検索',
    'embed_query':'クエリを埋め込む',
    'public_url':'公開URL',
    'iframe_embed':"Iframe埋め込み",
    'image_embed':'画像を埋め込む',
    'query_embed_sql_error':'テキストパラメータを含むクエリは埋め込むことができません',
    'auto_flush':'自動更新',
    'flush_hz':'更新頻度',
    'flush_never':'自動更新しない',
    'on_time': '時間による',
    'on_day':"日による",
    'ends': "終了日",
    'never':"永遠に",
    "on":"に",
    "every":"毎",
    'at':"で",
    'flush_schema':'データテーブルを更新',
    'save_success':'保存に成功しました',
    'save_failed':'保存に失敗しました',
    'trigger':'トリガー',
    'desc':"説明",
    'query_code':"クエリスクリプト",
    'add_edit_tag':"タグを追加/編集",
    'add_more_tag':"複数のタグを追加",
    'add_tag':'タグを追加',
    'archived':"アーカイブ済み",
    'draft':'ドラフト',
    'archived_info':'アーカイブされたクエリはダッシュボードに使用できず、リストや検索にも表示されません',
    'quit_with_not_save':"保存せずに終了してもよろしいですか?",
    'view_type':"ビュータイプ",
    'view_name':"ビュー名",
    'view_save_success':"ビューの保存に成功しました",
    'view_save_failed':'ビューの保存に失敗しました',
    'country':'全世界の国地図',
    'short_name':'略称',
    'full_name':'フルネーム',
    'abbreviated_name':"略称",
    'thank_you':'ありがとう',
    'setting_saved_success':'設定が保存されました',
    'share_info':'開発チームと匿名で使用統計データを共有しますか？',
    'help_redash':'自動的に使用統計データを送信し、開発チームが製品を改善するのを助けます',
    'redash_about_1':'ユーザー数、レポート数、ダッシュボード数、アラート数、ウィジェットとビュー数',
    'redash_about_2':'データソースの種類、アラートとビューの設定',
    'redash_info':'すべての送信データは統計数であり、敏感な個人データは含まれません。',
    'accept':'受け入れる',
    'reject':'拒否',
    'set_info_in':'いつでも入ることができます',
    'sys_setting':'システム設定',
    'sys_setting_add':'ページ、この設定を変更',
    'copy':'コピー',
    'copy_success':'コピー成功！',
    'copy_failed':'コピー失敗',
    'setting_info':'設定情報',
    'jdbc_info':'JDBC/ODBCを使用してDatabricksデータソースを使用できます。',
    'jdbc_download_name':'Databricks ODBC ドライバーダウンロード',
    'previous':"前へ",
    'done':'完了',
    'type':'タイプ',
    'type_select':'タイプ選択',
    'date_select':'日付選択',
    'datetime_select':"日付と時間を選択",
    'value':'値',
    'params_name':'パラメータ名',
    'params_ready_exist':'同名のパラメータが既に存在します！',
    'query_show_as':'レポートに表示',
    'new_params':'新しいパラメータ',
    'title':'タイトル',
    'text':'テキスト',
    'number':'数字',
    'select':'選択',
    'query_result':'レポート結果',
    'date_day':'日付（日）',
    'date_datetime':'日付（時分）',
    'date_time_second':'日付（時分秒）',
    'date_range_day':'日付範囲（日）',
    'date_range_datetime':'日付範囲（時分）',
    'date_range_time_second':'日付範囲（時分秒）',
    'list_select_help':'選択値（1行に1つ）',
    'wait_query':'選択値はレポートから来ます',
    'allow_multi':'複数選択を許可',
    'quotation':'引用値',
    'replace_query_info':'レポートスクリプトに表示',
    'default':'デフォルト',
    'single_quotation':'シングルクォート',
    'double_quotation':'ダブルクォート',
    'no_quotation':'引用符なし',
    'email_need_set':'メールサーバーが正しく設定されていません',
    'email_will_work':'この機能を使用するにはメールサーバーを設定する必要があります。',
    'add_favorite':'お気に入りに追加',
    'remove_favorite':'お気に入りから削除',
    'clear':'クリア',
    'select_all':'すべて選択',
    'guide_list_option':'ディレクトリ：パラメータ選択値',
    'guide_share_embed_dashboard':'ディレクトリ：ダッシュボードの共有と埋め込み',
    'guide_authentication':'ディレクトリ：認証',
    'help_share_anonymous_data':'ヘルプ：匿名で使用統計データを共有',
    'guide_amazon_athena':'ディレクトリ：Amazon Athenaの設定',
    'guide_set_bigquery':'ディレクトリ：BigQueryの設定',
    'guide_set_url_port':'ディレクトリ：URLネットワークデータインターフェースの設定',
    'guide_set_mongodb':'ディレクトリ：MongoDBの設定方法',
    'guide_set_google_spread':'ディレクトリ：Google Spreadsheetsの設定方法',
    'guide_set_google_analytics':'ディレクトリ：Google Analyticsの設定方法',
    'guide_set_axibase':'ディレクトリ：Axibase時間系列データベースの設定方法',
    'guide_set_query_result':'ディレクトリ：レポート結果計算データソースの設定方法',
    'guide_set_alert':'ディレクトリ：アラートの設定方法',
    'guide_set_mail':'ディレクトリ：メールサーバーの設定',
    'guide_set_notice':'ディレクトリ：カスタムアラート通知',
    'guide_favorite':'ディレクトリ：レポートまたはビューをお気に入り',
    'guide_query_permissions':'ディレクトリ：レポート権限の設定',
    'guide_formatting_number':'数字のフォーマット',
    'guide_menu_start':'ディレクトリ：スタート',
    'guide_dashboard':'ディレクトリ：ダッシュボード',
    'guide_query':'ディレクトリ：レポート',
    'guide_alert':'ディレクトリ：アラート',
    'click_here':'ここをクリック',
    'open_new_window':'新しいウィンドウで詳細情報を開く',
    'apply':"適用",
    'apply_change':'変更を適用',
    'new_dashboard_parm':'新しいダッシュボードパラメータ',
    'exist_dashboard_parm':'既存のダッシュボードパラメータ',
    'dashboard_param_error':'ダッシュボードパラメータのデータ型が一致しません',
    'widget_parm':'ウィジェットパラメータ',
    'static_value':'静的値',
    'enter_parm_name':'パラメータ名を入力してください',
    'select_parm':'パラメータを選択',
    'source':'ソース',
    'code_mast_have_value':'コードは空にできません',
    'exist_save_parm':'同名のパラメータが既に存在します',
    'edit_source_value':'ソースと値を編集',
    'title_set_hidden_in_widget':'静的値のタイトルはウィジェットに表示されません',
    'dashboard_parm':'ダッシュボードパラメータ',
    'code':'コード',
    'default_value':'デフォルト値',
    'no_option':'選択可能なデータはありません',
    'icon':"アイコン",
    'search_by_name':'名前でレポートを検索',
    'add':'追加',
    'selected':'選択された項目',
    'tag':'タグ',
    'loading_failed':'ロード状態が失敗しました、再試行してください。',
    'started_job':'進行中のタスク',
    'queen_job':'キューに入っているタスク',
    'queen_status':'キューの状態',
    'create_user':'ユーザー作成',
    'create_time':'作成時間',
    'run_time':'実行時間',
    'last_exec_datetime':"最後の実行時間",
    'update_schedule':'スケジュールを更新',
    'auto_update':'自動更新',
    'last_update_time':'最後の更新時間',
    'out_date_query':'期限切れのレポート',
    'alert_setting':'アラート設定',
    'add_alert_setting':'アラート設定を追加',
    'subscribed':'購読成功',
    'subscribe_failed':'購読失敗',
    'type_not_match_value':'取得列のタイプと閾値のタイプが一致しません',
    'type_not_match_condition':'取得列のタイプと条件のタイプが一致しません',
    'top_value':'最大取得値',
    'column_value':'列の値',
    'condition':'条件',
    'great_then':'より大きい',
    'great_and_equals':'以上',
    'less_then':'より小さい',
    'less_and_equals':'以下',
    'equals':'等しい',
    'not_equals':'等しくない',
    'threshold':'閾値',
    'delete_alert':'アラートを削除',
    'delete_alert_confirm':'本当にアラートを削除しますか？',
    'alert_unmute':'通知音をオンにする',
    'alert_mute':'通知音をオフにする',
    'are_you_sure':'本当によろしいですか？',
    'switch_warning':"デフォルトのテンプレートに切り替えると、カスタムテンプレートは破棄されます。",
    'use_default_template':'デフォルトのテンプレートを使用',
    'default_template':'デフォルトのテンプレート',
    'use_custom_template':'カスタムテンプレートを使用',
    'custom_template':'カスタムテンプレート',
    'subject':'件名',
    'content':'内容',
    'guide_format':'フォーマットガイド',
    'load_query_result':"レポート結果をロード",
    'open_query_in_new_tab':'新しいタブでレポートを開く',
    'query_not_setting':'このレポートは設定されていません',
    'recommend':'強く推奨',
    'query_setting_tip':'アラートを設定するには、自動更新を強く推奨します。自動更新されないレポートは、ユーザーが実行したときにのみ一度アラートを送信します。',
    'second':'秒',
    'minute':'分',
    'hour':'時間',
    'day':'日',
    'week':'週',
    'alert_one_time':'一度だけアラート',
    'alert_one_time_tip':'一度だけ 正常に戻るまで',
    'alert_every_time':'毎回実行時にアラート',
    'alert_every_time_tip':'毎回実行時にアラート 正常に戻るまで',
    'alert_most_once':'最大一度だけアラート',
    'alert_most_once_tip':'最大一度だけアラート：アラートがトリガーされた後',
    'notice_will_send':"通知が送信されます",
    'new_alert_tip':'新しいアラート',
    'can_not_edit_alert':'アラートを編集できません',
    'no_permission_readonly':"アラートを編集する権限がありません、現在は読み取り専用モードです。",
    'alert':'アラート',
    'alert_delete_success':'アラートの削除に成功しました',
    'alert_delete_failed':'アラートの削除に失敗しました',
    'set_mute_success':'ミュートに設定しました',
    'set_mute_failed':'ミュートの設定に失敗しました',
    'set_unmute_success':'通知音をオンに設定しました',
    'set_unmute_failed':'通知音をオンに設定に失敗しました',
    'saving':'保存中',
    'query':'レポート',
    'trigger_condition':'トリガー条件',
    'trigger_send_notice':'通知を送信',
    'template':'テンプレート',
    'setup_tip':'設定ヒント',
    'selector_query_tip':'監視したいレポートを選択してください（パラメータ付きのレポートは適用できません）',
    'status':'ステータス',
    'alert_setting_sure':'アラート設定が確認されました',
    'last_trigger_time':'最後のトリガー時間',
    'no_permission_edit_alert':'アラートを編集する権限がありません',
    'notice':'通知',
    'set':'設定',
    'custom':'カスタム',
    'notice_template':'通知テンプレート',
    'set_mute':'ミュートに設定',
    'set_unmute':'通知音をオンに設定',
    'alert_not_sent_info':'このアラートは通知を送信しません',
    'reset_alert_sent_info':'通知の送信を再開',
    'destination':'宛先',
    'set_alert_open_tab':'新しいタブでアラート設定を開く',
    'get_notice_event':'イベント通知を受け取る',
    'auto_flush_hz':'自動更新頻度',
    'flush':'更新',
    'stop_auto_flush':'自動更新を停止',
    'dashboard_archived':'ダッシュボードがアーカイブされました',
    'publish':'公開',
    'dis_en_able_fullscreen':'フルスクリーンの有効化/無効化',
    'share_dashboard_setting':'ダッシュボード共有設定',
    'saved':'保存済み',
    'retry':'再試行',
    'need_help':'ヘルプが必要',
    'create_first_dashboard':'最初のダッシュボードを作成',
    'see_big_picture':'全体像を見る',
    'show_my_favorite_dashboard':'お気に入りのダッシュボードを表示',
    'share_dashboard':'ダッシュボードを共有',
    'share_dashboard_tip':'すべての共有ダッシュボード',
    'open_share_dashboard_failed':'ダッシュボードの共有を開くのに失敗しました',
    'close_share_dashboard_failed':'ダッシュボードの共有を閉じるのに失敗しました',
    'allow_public':'すべての人が閲覧可能',
    'secret_address':'秘密のアドレス',
    'secret_address_tip':'テキストパラメータタイプを含むダッシュボードは共有できません、他のパラメータタイプに変更してください。',
    'dashboard_has_changed':'ダッシュボードが他のユーザーによって変更されました',
    'dashboard_has_changed_tip':'情報をバックアップして再読み込みしてください。',
    'all_dashboard':'すべてのダッシュボード',
    'my_dashboard':'私のダッシュボード',
    'my_favorite_dashboard':'お気に入りのダッシュボード',
    'search_dashboard':'ダッシュボードを検索',
    'abbreviated_name':"略称",
    'thank_you':'ありがとう',
    'setting_saved_success':'設定の保存に成功しました',
    'share_info':'開発チームと匿名で使用統計データを共有しますか？',
    'help_redash':'自動的に使用統計データを送信し、開発チームが製品を改善するのを助けます',
    'redash_about_1':'ユーザー数、レポート数、ダッシュボード数、アラート数、ウィジェットとビュー数',
    'redash_about_2':'データソースの種類、アラートとビューの設定',
    'redash_info':'すべての送信データは統計数であり、敏感なデータやプライベートデータは含まれません。',
    'accept':'受け入れる',
    'reject':'拒否',
    'set_info_in':'いつでも',
    'sys_setting':'システム設定',
    'sys_setting_add':'ページでこの設定を変更できます',
    'copy':'コピー',
    'copy_success':'コピー成功！',
    'copy_failed':'コピー失敗',
    'setting_info':'設定説明',
    'jdbc_info':'JDBC/ODBCを使用してDatabricksデータソースを使用できます。',
    'jdbc_download_name':'Databricks ODBC ドライバーのダウンロード',
    'previous':"前へ",
    'done':'完了',
    'type':'タイプ',
    'type_select':'タイプ選択',
    'date_select':'日付選択',
    'datetime_select':"日付と時間を選択",
    'value':'値',
    'params_name':'パラメータ名',
    'params_ready_exist':'同名のパラメータがすでに存在します！',
    'query_show_as':'レポートで表示',
    'new_params':'新しいパラメータ',
    'title':'タイトル',
    'text':'テキスト',
    'number':'数字',
    'select':'選択',
    'query_result':'レポート結果',
    'date_day':'日付（日）',
    'date_datetime':'日付(時分)',
    'date_time_second':'日付(時分秒)',
    'date_range_day':'日付範囲（日）',
    'date_range_datetime':'日付範囲(時分)',
    'date_range_time_second':'日付範囲(時分秒)',
    'list_select_help':'選択可能な値(1行に1つ)',
    'wait_query':'選択可能な値はレポートから',
    'allow_multi':'複数選択を許可',
    'quotation':'引用値',
    'replace_query_info':'レポートスクリプトで表示',
    'default':'デフォルト',
    'single_quotation':'シングルクォート',
    'double_quotation':'ダブルクォート',
    'no_quotation':'クォートなし',
    'email_need_set':'メールサーバーが正しく設定されていません',
    'email_will_work':'この機能を使用するにはメールサーバーを設定する必要があります。',
    'add_favorite':'お気に入りに追加',
    'remove_favorite':'お気に入りから削除',
    'clear':'クリア',
    'select_all':'すべて選択',
    'guide_list_option':'ガイド：パラメータの選択可能な値',
    'guide_share_embed_dashboard':'ガイド：ダッシュボードの共有と埋め込み',
    'guide_authentication':'ガイド：認証',
    'help_share_anonymous_data':'ヘルプ：匿名の使用統計データを共有',
    'guide_amazon_athena':'ガイド：Amazon Athenaの設定',
    'guide_set_bigquery':'ガイド：BigQueryの設定',
    'guide_set_url_port':'ガイド：URLネットワークデータインターフェースの設定',
    'guide_set_mongodb':'ガイド：MongoDBの設定方法',
    'guide_set_google_spread':'ガイド：Google Spreadsheetsの設定方法',
    'guide_set_google_analytics':'ガイド：Google Analyticsの設定方法',
    'guide_set_axibase':'ガイド：Axibase時間系列データベースの設定方法',
    'guide_set_query_result':'ガイド：レポート結果計算データソースの設定方法',
    'guide_set_alert':'ガイド：アラートの設定方法',
    'guide_set_mail':'ガイド：メールサーバーの設定',
    'guide_set_notice':'ガイド：カスタムアラート通知',
    'guide_favorite':'ガイド：レポートまたはビューをお気に入りに追加',
    'guide_query_permissions':'ガイド：レポート権限の設定',
    'guide_formatting_number':'数字のフォーマット',
    'guide_menu_start':'ガイド:開始',
    'guide_dashboard':'ガイド：ダッシュボード',
    'guide_query':'ガイド：レポート',
    'guide_alert':'ガイド：アラート',
    'click_here':'ここをクリック',
    'open_new_window':'新しいウィンドウで詳細情報を開く',
    'apply':"適用",
    'apply_change':'変更を適用する',
    'new_dashboard_parm':'新しいダッシュボードパラメータ',
    'exist_dashboard_parm':'既存のダッシュボードパラメータ',
    'dashboard_param_error':'ダッシュボードパラメータのデータ型が一致しません',
    'widget_parm':'ウィジェットパラメータ',
    'static_value':'静的値',
    'enter_parm_name':'パラメータ名を入力してください',
    'select_parm':'パラメータを選択してください',
    'source':'ソース',
    'code_mast_have_value':'コードは空にできません',
    'exist_save_parm':'同名のパラメータが既に存在します',
    'edit_source_value':'ソースと値を編集する',
    'title_set_hidden_in_widget':'静的値のタイトルはウィジェットに表示されません',
    'dashboard_parm':'ダッシュボードパラメータ',
    'code':'コード',
    'default_value':'デフォルト値',
    'no_option':'選択可能なデータがありません',
    'icon':"アイコン",
    'search_by_name':'名前でレポートを検索する',
    'add':'追加',
    'selected':'選択された項目',
    'tag':'タグ',
    'loading_failed':'ロードに失敗しました、再試行してください。',
    'started_job':'進行中のタスク',
    'queen_job':'キュー内のタスク',
    'queen_status':'キューの状態',
    'create_user':'ユーザーを作成する',
    'create_time':'作成時間',
    'run_time':'実行時間',
    'last_exec_datetime':"最後の実行時間",
    'update_schedule':'スケジュールを更新する',
    'auto_update':'自動更新',
    'last_update_time':'最後の更新時間',
    'out_date_query':'期限切れのレポート',
    'alert_setting':'アラート設定',
    'add_alert_setting':'アラート設定を追加する',
    'subscribed':'購読成功',
    'subscribe_failed':'購読失敗',
    'type_not_match_value':'取得列の型と閾値の型が一致しません',
    'type_not_match_condition':'取得列の型と条件の型が一致しません',
    'top_value':'最大取得値',
    'column_value':'列値を取得する',
    'condition':'条件',
    'great_then':'より大きい',
    'great_and_equals':'以上',
    'less_then':'より小さい',
    'less_and_equals':'以下',
    'equals':'等しい',
    'not_equals':'等しくない',
    'threshold':'閾値',
    'delete_alert':'アラートを削除する',
    'delete_alert_confirm':'本当にアラートを削除しますか？',
    'alert_unmute':'通知音をオンにする',
    'alert_mute':'通知音をオフにする',
    'are_you_sure':'本当によろしいですか？',
    'switch_warning':"デフォルトのテンプレートに切り替えると、カスタムテンプレートは破棄されます。",
    'use_default_template':'デフォルトのテンプレートを使用する',
    'default_template':'デフォルトのテンプレート',
    'use_custom_template':'カスタムテンプレートを使用する',
    'custom_template':'カスタムテンプレート',
    'subject':'主題',
    'content':'内容',
    'guide_format':'フォーマットガイド',
    'load_query_result':"レポート結果をロードする",
    'open_query_in_new_tab':'新しいタブでレポートを開く',
    'query_not_setting':'このレポートは設定されていません',
    'recommend':'強く推奨する',
    'query_setting_tip':'アラートを設定するには、自動更新を強く推奨します。自動更新されないレポートは、ユーザーが実行したときにのみ一度アラートを送信します。',
    'second':'秒',
    'minute':'分',
    'hour':'時間',
    'day':'日',
    'week':'週',
    'alert_one_time':'一度だけアラートする',
    'alert_one_time_tip':'一度だけ 正常に戻るまで',
    'alert_every_time':'毎回実行するたびにアラートする',
    'alert_every_time_tip':'毎回実行するたびにアラートする 正常に戻るまで',
    'alert_most_once':'最多一度だけアラートする',
    'alert_most_once_tip':'最多一度だけアラートする：アラートがトリガーされた後',
    'notice_will_send':"通知が送信されます",
    'new_alert_tip':'新しいアラート',
    'can_not_edit_alert':'アラートを編集できません',
    'no_permission_readonly':"アラートを編集する権限がありません、現在は読み取り専用モードです。",
    'alert':'アラート',
    'alert_delete_success':'アラートの削除に成功しました',
    'alert_delete_failed':'アラートの削除に失敗しました',
    'set_mute_success':'ミュートに設定しました',
    'set_mute_failed':'ミュートの設定に失敗しました',
    'set_unmute_success':'通知音をオンに設定しました',
    'set_unmute_failed':'通知音をオンに設定に失敗しました',
    'saving':'保存中',
    'query':'レポート',
    'trigger_condition':'トリガー条件',
    'trigger_send_notice':'通知を送信する',
    'template':'テンプレート',
    'setup_tip':'設定説明',
    'selector_query_tip':'監視したいレポートを選択してください（パラメータ付きのレポートには適用できません）',
    'status':'状態',
    'alert_setting_sure':'アラート設定が確認されました',
    'last_trigger_time':'最後のトリガー時間',
    'no_permission_edit_alert':'アラートを編集する権限がありません',
    'notice':'通知',
    'set':'設定',
    'custom':'カスタム',
    'notice_template':'通知テンプレート',
    'set_mute':'ミュートに設定する',
    'set_unmute':'通知音をオンに設定する',
    'alert_not_sent_info':'このアラートは通知を送信しません',
    'reset_alert_sent_info':'通知の送信を再開する',
    'destination':'目的地',
    'set_alert_open_tab':'新しいタブでアラート設定を開く',
    'get_notice_event':'イベント通知を受け取る',
    'auto_flush_hz':'自動更新頻度',
    'flush':'更新',
    'stop_auto_flush':'自動更新を停止する',
    'dashboard_archived':'ダッシュボードがアーカイブされました',
    'publish':'公開',
    'dis_en_able_fullscreen':'フルスクリーンにする/解除する',
    'share_dashboard_setting':'ダッシュボード共有設定',
    'saved':'保存されました',
    'retry':'再試行',
    'need_help':'ヘルプが必要',
    'create_first_dashboard':'最初のダッシュボードを作成する',
    'see_big_picture':'大きな画像を見る',
    'show_my_favorite_dashboard':'お気に入りのダッシュボードを表示する',
    'share_dashboard':'ダッシュボードを共有する',
    'share_dashboard_tip':'すべての共有ダッシュボード',
    'open_share_dashboard_failed':'ダッシュボードの共有を開くのに失敗しました',
    'close_share_dashboard_failed':'ダッシュボードの共有を閉じるのに失敗しました',
    'allow_public':'すべての人が閲覧できるようにする',
    'secret_address':'秘密のアドレス',
    'secret_address_tip':'テキストパラメータタイプを含むダッシュボードは共有できません、他のパラメータタイプに変更してください。',
    'dashboard_has_changed':'ダッシュボードが他のユーザーによって変更されました',
    'dashboard_has_changed_tip':'情報をバックアップして再読み込みしてください。',
    'all_dashboard':'すべてのダッシュボード',
    'my_dashboard':'私のダッシュボード',
    'my_favorite_dashboard':'お気に入りのダッシュボード',
    'search_dashboard':'ダッシュボードを検索する',
    'dashboard_filter':'ダッシュボードレベルのフィルタを使用する',
    'dashboard_widget_info':'独立したレポートビューウィジェットまたはテキストボックスをダッシュボードに連続して配置できます。',
    'data_source':'データソース  ',
    'new_data_source':'新しいデータソースを作成する',
    'no_datasource':'まだデータソースはありません',
    'datasource_delete_success':'データソースの削除に成功しました',
    'delete_datasource':'データソースを削除する',
    'delete_datasource_confirm':'本当にデータソースを削除しますか？',
    'connect_success':'接続に成功しました',
    'connect_failed':'接続テストに失敗しました',
    'connect_failed_tip':'データソースの接続中にエラーが発生しました、再試行してください。',
    'delete':'削除',
    'connect_test':'接続テスト',
    'no_alert_setting':"まだアラート設定が作成されていません。",
    'members':'メンバー',
    'full_access':'全アクセス',
    'view_only':'読み取り専用',
    'datasource_delete_failed':'データソースの削除に失敗しました',
    'change_datasource_permission_failed':'データソースの権限の変更に失敗しました',
    'search_database':'データソースを検索する',
    'group_datasource':'ロールデータソース',
    'group_no_datasource':'このロールにはデータソースがありません',
    'remove':'削除',
    'add_member':'メンバーを追加する',
    'search_member':'メンバーを検索する',
    'remove_member_failed':'メンバーの削除に失敗しました',
    'role_no_member':'このロールにはメンバーがいません',
    'role':'ロール',
    'built_in':'内蔵',
    'built_in_role_delete_tip':'内蔵ロールは削除できません',
    'my_favorite_query':'お気に入りのレポート',
    'email_send':'電子メールの確認メールが送信されました、受信トレイを確認してリンクをクリックし、メールアドレスが正しいことを確認してください。',
    're_send_email':'メールを再送する',
    'redash_welcome':'ようこそ',
    'redash_desc':'任意のデータソースに接続し、データを簡単に表示し共有します。',
    'redash_cut_data_tip':'レコード。レポートの結果セットが大きすぎる場合、レポートの結果セットが切り捨てられます。',
    'running':'実行中',
    'flush_time':'更新時間',
    'query_queue':'レポートがキューに入りました',
    'exec_query':'実行',
    'loading_query_result':'レポート結果をロード中',
    'query_run_error':'レポートの実行エラー',
    'update_time':'更新時間',
    'show':'表示',
    'edit_source':'ソースを編集する',
    'show_result_only':'結果のみを表示する',
    'no_datasource_cant_create_query':'データソースの権限がないため、レポートを作成できません。',
    'apply_permission':'<Link href="queries">レポートを表示</Link>するか、システム管理者に連絡して権限を申請できます。',
    'no_datasource_or_permission':'データソースが作成されていない、またはデータソースの権限がありません。',
    'first_create_datasource':'最初にデータソースを作成してからレポートを作成してください',
    'delete_view':'ビューを削除する',
    'delete_view_confirm':'本当にレポートビューを削除しますか？',
    'table':'テーブル',
    'add_view':'ビューを追加する',
    'please_exec_flush':'レポートを実行または更新してください',
    'no_permission_exec':'レポートを実行または更新する権限がありません',
    'archived_search':'アーカイブされたレポート',
    'archived_confirm':'レポートをアーカイブしますか',
    'archived_tip':'レポートがアーカイブされると、そのレポートとビューに関連するすべてのダッシュボードウィジェットとアラートが削除されます。',
    'archived_failed':'レポートはアーカイブされませんでした',
    'flush_error':'データソース構造の更新に失敗しました',
    'wait_retry':'しばらくしてから再試行してください',
    'query_save_publish_success':'レポートが保存および公開されました！',
    'leave_lost_warning':'query_save_publish_success',
    'leave_lost_confirm':'現在のページを離れてもよろしいですか？',
    'change_not_save':'変更が保存されませんでした',
    'query_has_change':'レポートは他のユーザーによって変更されました',
    'self_copy_save_and_reload':'変更を自分でコピーして保存し、再読み込みしてからメンテナンスしてください',
    'overwrite_query':'レポートを上書き',
    'overwrite_query_confirm':'レポートを上書きしてもよろしいですか？',
    'new_desc':'説明を追加',
    'query_format':'レポートスクリプトのフォーマット',
    'query_format_not_support':'現在のデータソースはフォーマットをサポートしていません',
    'exec_select_query':'選択したスクリプトを実行',
    'flush_now':'すぐに選択を更新',
    'toggle_screen':'全画面表示に切り替え',
    'open_in_redash':'開く',
    'save_as':'名前を付けて保存',
    'view_not_exist':'ビューは存在しません',
    'all_queries':'すべてのレポート',
    'my_queries':'私のレポート',
    'archived_query':'アーカイブされたレポート',
    'search_query':'レポートを検索',
    'get_data_from_datasource':'データソースからデータを取得',
    'script':'スクリプト',
    'snippet_script':'レポートスクリプト',
    'delete_snippet_script':'レポートスクリプトを削除',
    'delete_snippet_script_confirm':'レポートスクリプトを削除してもよろしいですか？',
    'delete_snippet_script_success':'スクリプトの削除に成功しました',
    'delete_snippet_script_failed':'スクリプトの削除に失敗しました',
    'new_snippet_script':'新しい一般的なレポートスクリプトを作成',
    'no_snippet_script':'まだ一般的なレポートスクリプトが作成されていません、クリック',
    'google_login':'Googleアカウントを統合',
    'allow':'許可',
    'google_login_tip':'あなたは',
    'google_login_auto_reg':'Googleアカウントで新規ユーザーを登録します。登録せずに直接Googleアカウントでログインすると、デフォルトのロールユーザーが自動的に作成されます。',
    'authentication':'ユーザー認証',
    'disable_password_tip':'ユーザー名とパスワードによるログイン方法は無効化されており、SSO統合認証方法のみがログインに対応しています。',
    'password_login':'パスワードでログイン',
    'enable_password_login_tip':'ユーザーが他のログイン認証を有効にした場合のみ、ユーザー名とパスワードによるログイン方法を無効にできます',
    'enable_password':'パスワードログインを有効にする',
    'enable_saml':'SAMLを有効にする',
    'disable':'無効化',
    'enable':'有効化',
    'static':'静的',
    'dynamic':'動的',
    'help_redash_improve_tip':'自動的に匿名の使用統計データを送信し、開発チームが製品を改善するのを助けます',
    'feature_flags':'特徴',
    'enable_multiple_owners_tip':'レポートダッシュボードが複数の所有者モードをサポートするように設定',
    'when_query_error_info_by_email':'レポートのバックエンド実行スケジュールが失敗した場合、メールで作成者に通知',
    'dashboard_language_tip':'レポートダッシュボードはマルチバイト言語の検索をサポート（中国語、日本語、韓国語、速度が遅い）',
    'date_format':'日付形式',
    'time_format':'時間形式',
    'table_view':'チャートビュー',
    'hidden_tool_bar':'描画モードバーを非表示',
    'too_short':"長さが短すぎます",
    'do_not_match':'パスワードが一致しません',
    'change_password':'パスワードを変更',
    'current_password':'現在のパスワード',
    'new_password':'新しいパスワード',
    'repeat_password':'パスワードを再入力',
    'email_send_error':'電子メールが送信できませんでした！',
    'email_not_setting':'メールサーバーが設定されていません、以下のアクティベーションリンクを自分で送信してください',
    'email_reset_password_send':'パスワードリセットメールを送信',
    'email_re_send_invite':'招待を再送',
    're_generate_api_key':'API KEYを再生成',
    're_generate_api_key_confirm':'API Keyを再生成してもよろしいですか？',
    'api_Key_has_been_regenerated':'API Keyが再生成されました！',
    'failed_to_regenerate_api_key':'API Keyの再生成に失敗しました！',
    'the_user_invitation_email_failed_to_be_sent':'ユーザー招待メールの送信に失敗しました。',
    'user_invitation_email_has_been_sent':'ユーザー招待メールが送信されました。',
    'the_email_server_is_not_configured':'電子メールサーバーが設定されていません。',
    'password_reset_email_has_been_sent':'パスワードリセットメールが送信されました。',
    'the_password_reset_email_was_not_sent_successfully':'パスワードリセットメールの送信に失敗しました。',
    'user_name':'ユーザー名',
    'enable_user':'ユーザーを有効にする',
    'disable_user':'ユーザーを無効にする',
    'invite_email':'メールでユーザーを招待',
    'invite_user':'ユーザーを招待',
    'active_time':'アクティベーション時間',
    'unpublished':"未公開",
  
  
    'connection_failed':'サーバーへの接続に失敗しました',
    'connection_success_tip':'サーバーへの接続に成功しました',
    'connection_failed_tip':'サーバーへの接続に失敗しました、再接続しています',
    'connection_success':'データベースの設定が完了しました',
    'select_data_source':'データソースを選択してください',
    'enter_your_question':'あなたの質問を入力してください',
    'connection_seems_lost':'接続が切れたようです、再試行してください',
    'stopping_generation':'生成を停止しています...',
    'please_fill_in_the_description':'説明を記入してください',
    'configuration_completed':'設定が完了しました',
    'start_the_dialogue':'会話を始めましょう',
    'report_generation_completed':'レポートの生成が完了しました',
    'stop_generation':'生成を停止',
    'send_me_instructions':'メッセージを送信',
    'start_use':'使用を開始',
    'init_config':'初期設定',
    'table_desc':'データテーブルの説明',
    'select_table':'データテーブルを選択...',
    'table_field_desc_edit':'データテーブルフィールドの説明を編集',
    'language_mode':"JP",
    'excel_upload':'csvデータソース',
    'data_analysis':'補助データ分析',
    'report_generation':'レポート生成',
    'report_list':'レポートリスト',
    
    'dashboard':'ダッシュボード',
    'offline':'オフライン',
    'online':'オンライン',
    'pending':'保留中',
    'temporary_dashboard':'一時的なダッシュボード',
    'history_dialogue':'歴史的な対話',
    
    'reset_dialogue':'対話をリセット',
    'reset_dialogue_confirm':'現在の対話をリセットして新しい対話を開始してもよろしいですか？',
    'new_dialogue':'新しい対話',
    'chat_start':'データ分析を開始するためにあなたのデータソースとテーブルを選択するか、または',
    'report_start':'レポート生成を開始するためにあなたのデータソースとテーブルを選択するか、または',
    'AutoPilot_start':'自動データ分析を開始するためにあなたのデータソースとテーブルを選択するか、または',
  
  
    'sheet_description':'データテーブルの説明を記入してください',
    'field_description':'フィールドの説明を記入してください',
  
    'source_tooltip':'あなたのデータソースを選択し、対応するテーブルとフィールドの説明を完了してください。DeepBIは、人間の言語を操作可能な操作に変換し、現実世界のタスク、例えばデータ関連のタスクを完成させるのを助けます。',
    'source_first_tooltip':'Agentがタスクをより良く完成させるために、テーブルとフィールドの注釈を完了してください。',
    'source_second_tooltip':'上記の注釈は大規模モデルの検査に通過していません、修正して再提出してください',
  
    'fail':'不合格',
    'pass':'合格',
    'detection':'検出',
    'description':'説明',
    'field_name':'フィールド名',
    'universal_csv':'汎用csv',
    'ai_understanding_data':'AIがデータを理解しようとしています、お待ちください...',
    'start_your_dialogue':'レポートを生成するためにあなたの対話を開始してください',
    'no_dialogue':'対話記録はありません',
    'new_Query':'新しいレポート',
    'empty_query':'空のステートメントは実行できません。',
    'formatting':'フォーマット',
    'border':'境界',
    'exterior':'外観',
  
    'left_align':"左揃え",
    'center':"中央揃え",
    'right_align':'右揃え',
    'formatting_numbers':"数字のフォーマット",
    'formatting_dates_and_times':"日付と時間のフォーマット",
    'x_axis_label':"X軸のラベル",
    'y_axis_label':"Y軸のラベル",
    'scale':'スケール',
    'auto_detect':'自動検出',
    'datetime':'日付時間',
    'linear':'線形スケール',
    'logarithmic':'対数スケール',
    'category':'カテゴリスケール',
    'auto':'自動',
    'min_value':'最小値',
    'max_value':'最大値',
    'x_column':'X軸',
    'y_column':'Y軸',
    'group_by':'グループ化',
    'errors_column':'Y軸のエラー',
    'color_column':'色',
    'choose_columns...':'列を選択（複数選択可能）...',
    'choose_column..':'列を選択...',
    'color':'色',
    'series':'シリーズ',
    'bubble_size_coefficient':'バブルサイズの係数',
    'bubble_size_proportional_to':'バブルサイズの比例',
    'direction':'方向',
    'legend_placement':'凡例の配置',
    'legend_items_order':'凡例の順序',
    'stacking':'データの積み上げ',
    'missing_and_NULL_values':'値がないまたはNULLの値',
    'color_scheme':'配色スキーム',
    'choose_color_scheme':'配色スキームを選択',
    'min_color':'最小値の色',
    'max_color':'最大値の色',
    'data_labels':'データラベル',
    'order':'順序',
    'label':'ラベル',
    'y_axis':'Y軸',
    'x_axis':'X軸',
    'left_y_axis':'左のY軸',
    'right_y_axis':'右のY軸',
    'reverse_order':'昇順/降順',
    'sort_values':'値を並べ替え',
    'align_Y_axes_at_zero':'Y軸をゼロ目盛りで揃える',
    'columns':'列の設定',
    'grid':'グリッド設定',
    'items_per_page':'1ページあたりの行数',
    'toggle_visibility':'表示/非表示を切り替え',
    'Link':'リンク',
    'Image':'画像',
    'URL_template':'URLテンプレート',
    'Text_template':'テキストテンプレート',
    'Title_template':'タイトルテンプレート',
    'Open_in_new_tab':'新しいタブで開く',
    'All_columns_can_be_referenced_using':'すべての列は関連付けて使用できます、次のようにしてください',
    'syntax':'構文。',
    'This_syntax_is_applicable_to_URL_Text_and_Title_options':'この構文はURL、テキスト、タイトル設定にも適用可能です。',
    'Use':'使用',
    'to_reference_current_this_column':'現在の列を参照。',
    'Width':'幅',
    'Height':'高さ',
    'Leave_empty_to_use_default_value':'空白の場合、デフォルト値を使用します。',
    'Any_positive_integer_value_that_specifies_size_in_pixels':'正の整数ピクセル値を入力します。',
    'Size':'サイズ',
    'Boolean':'ブール',
    'Highlight_links':'リンクを強調表示',
    'Allow_HTML_content':"HTMLコンテンツを許可",
    'Number_format':'数値形式',
    'Date_Time_format':'日付時間形式',
    'Value_for':"値",
    'Error_while_rendering_visualization':'ビジュアライゼーションのレンダリング中にエラーが発生しました。',
    'Show_Data_Labels':'データラベルを表示',
    'Percent_Values_Format':'パーセンテージ形式',
    'Data_Labels':'データラベル',
    'using':'使用',
    'Also_all_query_result_columns_can_be_referenced':'すべてのクエリ結果列も参照可能',
    'Horizontal_Chart':'水平チャート',
    'Area':'エリア',
    'Diameter':'直径',
    'Counterclockwise':'反時計回り',
    'Clockwise':'時計回り',
    'Hide_legend':'凡例を非表示',
    'Right':'右',
    'Bottom':'下',
    'Normal':'通常',
    'Reversed':'逆順',
    'Show_All_Points':'すべてのポイントを表示',
    'Disabled':'無効',
    'Stack':'スタック',
    'Normalize_values_to_percentage':'パーセンテージに値を正規化',
    'Do_not_display_in_chart':'チャートに表示しない',
    'Convert_to_0_and_display_in_chart':'0に変換してチャートに表示',
    'Left':'左',
    'Show_Labels':'ラベルを表示',
    'North_East_Latitude_and_Longitude':'北東の緯度と経度',
    'South_West_Latitude_and_Longitude':'南西の緯度と経度',
    'Clustering_Mode':'クラスタリングモード',
    'Steps':'ステップ',
    'No_Value_Color':'値なしの色',
    'Background_Color':'背景色',
    'Borders_Color':'境界色',
    'Stage_Value':'ステージ値',
    'Map':'地図',
    'Key_Column':'地理区域の値',
    'Target_Field':'マップ対応フィールド',
    'Value_Column':'データ値',
    'Time_Column_Title':'時間のタイトル',
    'People_Column_Title':'統計値のタイトル',
    'Stage_Column_Title':'ステージタイトル形式',
    'No_Value_Placeholder':'値なしのプレースホルダー',
    'Show_Tooltips':'ツールチップを表示',
    'Daily':'毎日',
    'Weekly':'毎週',
    'Monthly':'毎月',
    'Fill_gaps_with_zeros':'ギャップをゼロで埋める',
    'Show_data_as_is':'そのままデータを表示',
    'Time_Interval':'時間間隔',
    'Mode':'モード',
    'Items_Count_Limit':'最大ステージ数',
    'Min_Percent_Value':'パーセンテージの最小値',
    'Max_Percent_Value':'パーセンテージの最大値',
    'number_of_times_this_sequence_occurred':'数値',
    'stage_5_value_or_null':'ステージ5の値（null可）',
    'stage_4_value_or_null':'ステージ4の値（null可）',
    'stage_3_value_or_null':'ステージ3の値（null可）',
    'stage_2_value_or_null':'ステージ2の値（null可）',
    'stage_1_value':'ステージ1の値',
    'Option':'オプション',
    'stage_name':'ステージ名',
    'what_stage_in_sequence_this_is_1_2':'シーケンス内のステージ（例：1, 2, ...）',
    'sequence_id':'シーケンスID',
    'This_visualization_expects_the_query_result_to_have_rows_in_one_of_the_following_formats':'このビジュアライゼーションは、クエリ結果が以下の形式のいずれかであることを期待しています',
    'Show_Column_Totals':'列合計を表示',
    'Show_Row_Totals':'行合計を表示',
    'Show_Pivot_Controls':'ピボットコントロールを表示',
    'Icon_Color':'アイコンの色',
    'Enter_an_icon_name_from':'アイコンライブラリからアイコン名を入力',
    'Examples':'例',
    'Leave_blank_to_remove':'空白にすると自動的に削除されます。',
    'Map_Tiles':'マップタイル',
    'Markers':'マーカー',
    'Cluster_Markers':'クラスターマーカー',
    'Override_default_style':'デフォルトのスタイルを上書き',
    'Shape':'形状',
    'Circle':'円',
    'Circle_Dot':'円ドット',
    'Square_Dot':'四角ドット',
    'Square':'四角',
    'Longitude_Column_Name':'経度の値',
    'Latitude_Column_Name':'緯度の値',
    'Popup_template':'ポップアップテンプレート',
    'Show_popup':'ポップアップを表示',
    'Tooltip_template':'ツールチップテンプレート',
    'Show_tooltip':'ツールチップを表示',
    'Legend_Text_Alignment':'凡例のテキスト配置',
    'Legend_Position':'凡例の位置',
    'Show_Legend':'凡例を表示',
    'Value_Placeholder':'値のプレースホルダー',
    'Value_Format':'値の形式',
    'auto_pilot':'自動データ分析',
    'report_name':'レポート名',
    'report_desc':'レポートの説明',
    'report_name_placeholder':'レポート名を入力してください',
    'report_desc_placeholder':'レポートの説明を入力してください',
    'history_autopilot':'履歴分析',
    'task_status':'タスクの状態',
    'no_analysis_available':'分析レポートはありません',
    'success':'成功',
    'fail':'失敗',
    'generating':'生成中',
    'waiting':'待機中',
    'all_autopilot':'すべての分析レポート',
    'submit_success':'送信成功',
    'submit_success_tip':'履歴分析で確認できます',
    'submit_fail':'送信失敗',
    'download':'ダウンロード',
    'please_enter_api_key':'Api Keyを入力してください',
    'please_enter_api_host':'Api Hostを入力してください',
    'confirm_delete':'削除を確認',
    'confirm_delete_tip':'このプロジェクトを削除してもよろしいですか？',
  
    'please_complete_report_name_and_report_desc':'レポート名とレポートの説明を完了させて、Agentが自動データ分析を行うようにしてください',
    'report_name_and_report_desc_tip':'レポート名は生成されるレポートのタイトルとして使用されます。レポートの説明はAgentに自動データ分析の大方向を提供し、レポートの分析範囲を定めます。送信をクリックすると、レポートタスクが作成されます',
    'report_name_tip':'レポート名は生成されるレポートのタイトルとして使用されます',
    'report_desc_tip':'レポートの説明はAgentに自動データ分析の大方向を提供し、レポートの分析範囲を定めます',
    'task_processing':'タスク処理中...',
    'style':'スタイル',
    "region": "地域",
    "column": "列",
    "option": "オプション",
    'click_here_to_get_apikey':'ここをクリックしてApiKeyを取得',
    'dashboards_prettify':'ダッシュボードの美化',
    'dashboards_prettify_all':'すべてのダッシュボードを美化',
    'delete_success':'削除成功',
    'delete_fail':'削除失敗',
    'no_dashboard_data':'ダッシュボードデータがありません',
    'prettify_dashboard':'一括美化',
    'coming_soon':'近日公開',
    'example1':'例1',
    'example2':'例2',
    'example3':'例3',
    'more':'もっと見る',
  }