from .prompt_matplotlib import MYSQL_MATPLOTLIB_TIPS_MESS
from .prompt_echarts import EXCEL_ECHART_TIPS_MESS, MYSQL_ECHART_TIPS_MESS, POSTGRESQL_ECHART_TIPS_MESS, MONGODB_ECHART_TIPS_MESS, CSV_ECHART_TIPS_MESS

__all__ = [
    "EXCEL_ECHART_TIPS_MESS",
    "MYSQL_ECHART_TIPS_MESS",
    "MYSQL_MATPLOTLIB_TIPS_MESS",
    "POSTGRESQL_ECHART_TIPS_MESS",
    "MONGODB_ECHART_TIPS_MESS",
    "CSV_ECHART_TIPS_MESS"
]
